### ISSUE TITLE
Problem with sharing image to facebook

### ISSUE THREAD

**Issue by didiksetia1** [facebook/facebook-sdk-for-unity#1]
I have problem in sharing image. I did the code following the instruction in this tutorial https://developers.facebook.com/docs/unity/reference/current/FB.API

I did it like this:

public static string ScreenShotName() 
{
		return string.Format("{0}/mizanRPG/mizanRPG_{1}.png", 
		                     Application.dataPath, 
		                     System.DateTime.Now.ToString ("yyyyMMdd_HHmmss"));
}

private IEnumerator ShareImage()
{
		yield return new WaitForEndOfFrame();

		Texture2D screenShot = new Texture2D(Screen.width , Screen.height,    TextureFormat.RGB24, false);
		screenShot.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
		screenShot.Apply ();
		byte[] bytes = screenShot.EncodeToPNG();
		string filename = ScreenShotName();
		File.WriteAllBytes(filename, bytes);
		Debug.Log(string.Format("Took screenshot to: {0}", filename));
		setFotoPath (filename);

		var wwwForm = new WWWForm();
		wwwForm.AddBinaryData("image", bytes, "mizanRPG.png");
		wwwForm.AddField("message", "herp derp.  I did a thing!  Did I do this right?");

		FB.API("me/photos", Facebook.HttpMethod.POST, Callback, wwwForm);
}

void Callback(FBResult result)
{
	if (result.Error != null)
       {
	      Debug.LogError (result.Error);
	      EtceteraAndroid.showToast ("gagal post", true);
       } 
      else 
     {
	EtceteraAndroid.showToast("sukses upload foto", true);
	}
}

The problem is, after i make sure that fb is logged in, and proceed to share an image, but when I check my fb, nothing happen. The callback doesn't return anything. 
Did I do something wrong?

I hope this post reach you.
Thank you.

**Comment by swiese** [comment]
The code you show isn't valid for v7.1.0 There is no FBResult. You should have a IGraphResult instead. 

 Make sure you cleaned up your project when you updated to 7.1.0 following this guide https://developers.facebook.com/docs/unity/upgrading-7.x

**Comment by didiksetia1** [comment]
thanks for the answer, 

i have a new problem. when i build to apk, sometimes i got error after got apk, 
The error goes:
"Your Android setup is not correct. See Settings in Facebook menu.
UnityEditor.HostView:OnGUI()"

but before there is no error like that, i just try to rebuild again and got that message, 
i try to regenerate android manifest, but still error
i try to make the new project and make same code, it still error
pls let me know what should i do.

**Comment by sarthakshah7** [comment]
if above code is working perfectly then which type login permission should i use to log into the facebook ? currently i am using facebook sdk v7.2.2 (latest one) and when I run above code facebook responded with an error "403:forbidden", do i need loginwithpublishpermission with publish action ? hep me on this.
