### ISSUE TITLE
SDK 7.10.0 Block unity player settings window

### ISSUE THREAD

**Issue by Liviuss76** [facebook/facebook-sdk-for-unity#102]
After importing sdk v.7.10.0 unity will not allow to view player settings window content.

On accessing player settings window, on console you can see error:
`FBException: Property <uploadAccessToken> is missing in the current FB SDK
UnityEditor.Facebook.FacebookSettingsExtension.CheckFBSettingsProperty (System.String propertyName) (at C:/buildslave/unity/build/PlatformDependent/Facebook/Extensions/Managed/FacebookSettingsExtension.cs:55)
UnityEditor.Facebook.FacebookSettingsExtension.InitFacebookSettings () (at C:/buildslave/unity/build/PlatformDependent/Facebook/Extensions/Managed/FacebookSettingsExtension.cs:86)
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.PlayerSettingsEditor.BeginSettingsBox (Int32 nr, UnityEngine.GUIContent header) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/PlayerSettingsEditor/PlayerSettingsEditor.cs:603)
UnityEditor.PlayerSettingsEditor.ResolutionSectionGUI (BuildTargetGroup targetGroup, ISettingEditorExtension settingsExtension, Int32 sectionIndex) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/PlayerSettingsEditor/PlayerSettingsEditor.cs:789)
UnityEditor.PlayerSettingsEditor.OnInspectorGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/PlayerSettingsEditor/PlayerSettingsEditor.cs:532)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1240)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

Reproduced on Unity 2017.1, Unity 2017.2.beta
After downgrading to 7.9.4, everything vent fine.
Related thread on unity forum: https://forum.unity.com/threads/unable-to-access-player-settings.456662/#post-3218167

**Comment by filipinyo** [comment]
7.10 worked... but now when I've upgraded unity I have a same problem... any other solutions?

**Comment by D3m0n92** [comment]
Same problem.

**Comment by wenderRondonia** [comment]
7.10.1 fixed this issue! https://developers.facebook.com/docs/unity/change-log#v7_10_1
