### ISSUE TITLE
FacebookSdkNotInitializedException issue

### ISSUE THREAD

**Issue by FedericoLaGreca** [facebook/facebook-sdk-for-unity#11]
Hello,
We have an issue with the Unity FB SDK. On Android some devices the app crashes with a native exception:
com.facebook.FacebookSdkNotInitializedException

full stacktrace:
com.facebook.internal.Validate.sdkInitialized (Validate.java:136)
com.facebook.FacebookSdk.getApplicationContext (FacebookSdk.java:423)
com.facebook.AccessTokenManager.getInstance (AccessTokenManager.java:84)
com.facebook.AccessToken.getCurrentAccessToken (AccessToken.java:144)
com.facebook.appevents.AppEventsLogger.<init> (AppEventsLogger.java:657)
com.facebook.appevents.AppEventsLogger.newLogger (AppEventsLogger.java:418)
com.facebook.login.LoginMethodHandler.logWebLoginCompleted (LoginMethodHandler.java:96)
com.facebook.login.KatanaProxyLoginMethodHandler.handleResultOk (KatanaProxyLoginMethodHandler.java:101)
com.facebook.login.KatanaProxyLoginMethodHandler.onActivityResult (KatanaProxyLoginMethodHandler.java:82)
com.facebook.login.LoginClient.onActivityResult (LoginClient.java:151)
com.facebook.login.LoginFragment.onActivityResult (LoginFragment.java:162)
android.support.v4.app.FragmentActivity.onActivityResult (FragmentActivity.java:165)
dalvik.system.NativeStart.main (NativeStart.java)

We are pretty sure that every call to FB is made after the init method has called the callback, and we even tried to force a call before the init procedure and had a different exception thrown, inside Unity and not native.

Also, we're seeing this on 700 users out of 33000 (these users have the problem every time they use the app, and it doesn't look like it's specific of an Android version or device), so it's not (we think) an implementation problem, as Unity thinks the SDK is initialized, but the native side says it's not. What can we do about it?

Thank you

**Comment by AlessandroLacroce** [comment]
+1 for this!

**Comment by swiese** [comment]
For better tracking and reporting you can report bugs to 
https://developers.facebook.com/bugs

I do know we have one bug that we will look to fix in the next release where if the Unity Activity is destroyed while switching to the facebook app to login, most likely due to low memory, on callback the app will crash with sdk initialized failed since this call hasn't been made since restarting the activity. Otherwise I don't have enough info to debug this issue with only a stack trace.
