### ISSUE TITLE
FB.Mobile.AppInvite does not show notification to friend.

### ISSUE THREAD

**Issue by hellboys8055** [facebook/facebook-sdk-for-unity#114]
i have implemented FB.Mobile.AppInvite for android. it returns successfully request sent, but on other side friend doesn't receives request.

can anyone help me on this,

**Comment by mingflifb** [comment]
Notifications are not guaranteed, and there are a host of reasons why they might not be sent. If you believe there's a bug, then feel free to file one at developers.facebook.com/bugs.
