### ISSUE TITLE
Sharing links to feed

### ISSUE THREAD

**Issue by sonicsmith** [facebook/facebook-sdk-for-unity#119]
I'm at a loss to how we are meant to do basic posts on the FB feed.
I want to post a link to my mobile game, and a a description / message to say what score the player got.
When I try to do this, my description isn't displayed. Basic searches of this issue make it sound like it can't be done now?!

Is Facebook not allowing messages to be attached to the posts anymore? Is there a way to get around this?

**Comment by twoodhull** [comment]
@sonicsmith 
Try visiting: https://developers.facebook.com/docs/unity/reference/current/FB.FeedShare/

**Comment by sonicsmith** [comment]
Where does the custom message go though?
```
public static void FeedShare(
  string toId = "",
  Uri link = null,
  string linkName = "",
  string mediaSource = "",
  FacebookDelegate<IShareResult> callback = null
)
```

**Comment by twoodhull** [comment]
The Docs seem to be missing all of the parameters. Here is the declaration of `FB.FeedShare` https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/FB.cs#L492-L542

**Comment by sonicsmith** [comment]
Thanks for the help. I tried using this already, and it stripped out the `linkCaption` and `linkDescription`.
Maybe I was doing something wrong, so I will try again, but when I research online, I found people saying that FB strips out that info now.
Could anyone else confirms this works?

**Comment by sonicsmith** [comment]
Just tried again then and I get the link posted, and nothing else. The FB status prompt is there for the user to fill in their message, but I was hoping for the app to propagate it.
[SCREENSHOT](https://imgur.com/a/dKeAc)
(Ignore that my example screenshot is posting a non-existent link)

**Comment by mingflifb** [comment]
Those fields have been deprecated: https://developers.facebook.com/docs/graph-api/changelog/version2.9#gapi-90-links

**Comment by sonicsmith** [comment]
Thanks @mingflifb . This is sadly what I thought. So the FB SDK has no way to share something in an informative way now? This seems like a major fail for the SDK. For just sharing something, one should probably not bother with the FB SDK at all?

**Comment by mingflifb** [comment]
If you share a link, you can use our standard meta tags to trigger a preview. What was deprecated is the ability to override what the link really represents.

See https://developers.facebook.com/docs/sharing/webmasters/crawler/ for more details.

**Comment by sonicsmith** [comment]
Thanks a lot @mingflifb , this has answered my question.
