### ISSUE TITLE
FB.Mobile.AppInvite not working, and logging "The operation couldn't be completed. (com.facebook.sdk.core error 9)"

### ISSUE THREAD

**Issue by patdev88** [facebook/facebook-sdk-for-unity#139]
I'm using facebook-unity-sdk-7.9.0 on an iOS app, developed with Unity 5.5.4p5. I cannot upgrade Unity at the moment.
I created a new Test App from developers.facebook.com, and used its bundle ID and AppID (triple checked them) to build an app containing the test scenes delivered with this unitypackage. Then I added my user to the test user list.
The app builds correctly.
Starts correctly.
FB.Init() runs successfully.
The Login runs succesfully.
Then I click on the 'App Invites' button. Then on the 'iOS Invite' button, and I immediately get this error in the logs:
```Facebook.Unity.AppInviteResult
AppInviteResult:
    Error: The operation couldn't be completed. (com.facebook.sdk.core error 9)
    RawResult: {"error":"The operation couldn't be completed. (com.facebook.sdk.core error 9)
","callback_id":"4"}
    Cancelled: False
```
I even tried on an app "from scratch". I don't know what else to try.

**Comment by PinguN00t** [comment]
Same problem here, no problem on Android, error on iOS :  

```
Error: The operation couldn’t be completed. (com.facebook.sdk.core error 9.)
	RawResult: {"error":"The operation couldn’t be completed. (com.facebook.sdk.core error 9.)","callback_id":"5"}
	Cancelled: False
```

**Comment by hippogamesunity** [comment]
Just upgraded to the latest version. Tried fully remove my old instance. Got black screen on AppInvite call on Android.

**Comment by patdev88** [comment]
Good news everyone! (NOT)

https://developers.facebook.com/docs/app-invites/android/

>With the release of the Facebook SDK version 4.28.0, App Invites is deprecated. **It will be supported until February 5, 2018.**

**Comment by hippogamesunity** [comment]
"Sorry, the link you followed may be broken, or the page may have been removed."

**Comment by hippogamesunity** [comment]
And also what is the alternative for Unity plugin?

**Comment by patdev88** [comment]
Yeah, sorry about the broken link, point is that they dropped support on February 5. Btw you can see it also on Xcode. The function is flagged as deprecated.
The closer similar alternative I know is [app requests](https://developers.facebook.com/docs/unity/reference/current/FB.AppRequest).
If you send an empty app request, it acts like a, AppInvite.

**Comment by ShwetaChauhan18** [comment]
I also face same problem. So, any solution for this?
