### ISSUE TITLE
7.11.x missing 'Facebook.Unity.Canvas' on WebGL 

### ISSUE THREAD

**Issue by MoinTom** [facebook/facebook-sdk-for-unity#147]
Hey guys,
after upgrading the SDK to 7.11.x (both 7.11 and 7.11.1) i get the following error when running the app:
> FileNotFoundException: Could not load file or assembly 'Facebook.Unity.Canvas' or one of its dependencies. The system cannot find the file specified.

I already tried to adjust link.xml because i thought it might be a stripping issue, but it didn't help.
```
<assembly fullname="Facebook.Unity.Canvas" ignoreIfMissing="1">
  <type fullname="Facebook.Unity.Canvas.*" preserve="all"/>
</assembly>
<assembly fullname="Facebook.Unity.*" ignoreIfMissing="1">
  <type fullname="Facebook.Unity.*" preserve="all"/>
</assembly>
```

If somehow relevant i am using Unity 2017.3.p4 

Best Wishes
MoinTom

**Comment by cochler** [comment]
Same for me

**Comment by IARI** [comment]
yep - same here

**Comment by binouze** [comment]
Same here, very annoying

**Comment by lwx5924** [comment]
same for me.

**Comment by IARI** [comment]
no commits for 28 days on this repository - is that normal?

**Comment by Deathwing** [comment]
I pushed fixes for Login and LogAppEvent, can be found on the Pull Request and also on my Repo.

**Comment by tallior** [comment]
is this issue only with 7.11.x and higher? what if i downgrade to 7.10.1 ?

**Comment by Deathwing** [comment]
It should not help, any version above 7.9.X is incorrect, they changed the general WebGL behavior in 7.10.0 since them it was not resolved.

**Comment by MoinTom** [comment]
I downgraded to 7.10.1 and it worked for me.

**Comment by darekrusin** [comment]
Same with me. I've ran into this error with 7.11.1, downgraded to 7.10.1 and WebGL builds (Unity, targeting Facebook app) seems to be working fine now.

**Comment by Deathwing** [comment]
Oh yeah you both are right. The issue was introduced in 7.11 with the changes to thr ExternalAPI on WebGl (thought ideas on 7.10). But if you need to use 7.11, just use my changes to the 2 webgl files and it will also work. (7.11 is also more elegant because the Facebook code is not getting directly injected into your html anymore.)

**Comment by binouze** [comment]
still the same problem with the latest version 7.12

**Comment by rankorn** [comment]
Anyone opened a bug on Facebook for this? is so, whats the bug id?

**Comment by rankorn** [comment]
Here is a facebook bug I opened myself. Please subscribe:
https://developers.facebook.com/support/bugs/208041073313482/

**Comment by MoinTom** [comment]
Seem to be fixed with v7.12.1

**Comment by rankorn** [comment]
Unfortunately they introduced a new bug:
https://developers.facebook.com/support/bugs/1821608858133184/

So be prepared if you decide to update.

**Comment by PeeGee85Spil** [comment]
Getting the same bug using FB SDK 7.13.0, fix posted above does not work. Not solved.

**Comment by UncleJey** [comment]
7.13.0 plugin some error. not solved.

**Comment by KylinChang** [comment]
Hey all, the issue can be fixed with following steps:
1. In Unity IDE, go to director Assets->FacebookSDK->Plugins, where there are several plugins including Android, iOS, Canvas;
2. Choosing correct platform for plugin, for example, goto Android director and only chooses "Android" for plugins in the inspector
