### ISSUE TITLE
Detailed description of each library from package

### ISSUE THREAD

**Issue by Firstborned** [facebook/facebook-sdk-for-unity#149]
Good day!

Where I can find detailed description of each library and what functionality it contains.
For example, I need only facebook analytics. What libraries should I import, to get this?
And I don't need other Facebook stuff, only analytics!

Thanks in advance!

**Comment by kthai** [comment]
You can view the Unity documents here https://developers.facebook.com/docs/unity/reference/current/FB.LogAppEvent.

For more details about how App Events work and fields, see https://developers.facebook.com/docs/app-events

**Comment by Firstborned** [comment]
You didn't get my thoughts.
When you importing facebook for unity, there are too much libraries importing.
What I wan't - see description of each library, which are in included in sdk for unity.
For example:
facebook-core - corresponds for what?
facebook-common - corresponds for what?
and so on.
