### ISSUE TITLE
Facebook Deffered Deep Linking with FB Unity3D SDK setup

### ISSUE THREAD

**Issue by Solid-Metal** [facebook/facebook-sdk-for-unity#15]
not really an issue with the SDK quite honesly, but AFAIK theres no documentation in the SDK for doing this thing

so i made a game using Unity 5.2 with integrating FB SDK with it
i already made the app page, and already done integrating it on my android/iOS app, everything done quite well
now i want to use Facebook ads to boost my game even further
i go to this page http://developers.facebook.com/docs/app-ads/sdk , to verify if my game ready for ads setup

and i got this problem :
![e6ewe](https://cloud.githubusercontent.com/assets/10932705/11902569/54fd7ea8-a5e5-11e5-853b-84bd78dfc2d9.png)

i honestly don't know anything about defered deep link, i already tried googling and youtube but still found nothing

the documentation on Android : https://developers.facebook.com/docs/reference/android/current/class/AppLinkData/#fetchDeferredAppLinkData

and iOS : https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAppLinkUtility/#fetchDeferredAppLink

didnt help at all,

even when i search about it for FB unity SDK, i only ended up on this documentation page : https://developers.facebook.com/docs/unity/reference/current/FB.GetAppLink which didn't explain anything about deeplink...

i already made the app.me facebook link for my app, and already use it on share feature on my app, but still it didn't count as defered deep link, which is very confuse me

i stuck here about couple days now, if anyone know regarding this, please enlighten me

thank you in advance :)

**Comment by swiese** [comment]
Here is the documentation on this method for unity. 

https://developers.facebook.com/docs/unity/reference/current/FB.Mobile.FetchDeferredAppLinkData
