### ISSUE TITLE
Mach o link Error in v.7.11.1

### ISSUE THREAD

**Issue by Oni22** [facebook/facebook-sdk-for-unity#157]
Hi,

Currently I'm trying to implement the facebook sdk but when I try to build in xCode I got this Error:
![asdasdasd](https://user-images.githubusercontent.com/17254331/38778289-f3aba0c4-40b7-11e8-981e-dce501399eba.PNG)

I search and found a thread about this issue but in the release notes is written that this version should fix this linker error... any ideas?

**Comment by KylinChang** [comment]
The issue should be fixed in the latest SDK. Close the issue.
