### ISSUE TITLE
MockLoginDialog unable to run from maintained code

### ISSUE THREAD

**Issue by jdmiranda** [facebook/facebook-sdk-for-unity#16]
I"m trying to make my own test harness for logging into facebook and linking aws. The problem I'm having is when I call FB.LogInWithReadPermissions (new List<string> () { "public_profile", "email", "user_friends" }, FooBar); 

FB.LoginWithReadPermissions wants to be called from OnGui. With the new canvas system are there plans to change this from being inside OnGui?

**Comment by swiese** [comment]
We're aware of this issue and it will be fixed in the next release. 
https://developers.facebook.com/bugs/412005298997939/
