### ISSUE TITLE
Graph API version Issue

### ISSUE THREAD

**Issue by num0n1** [facebook/facebook-sdk-for-unity#162]
I'm trying to find out which graph api version I'm using for my app, 
We are using SDK 7.9.4, FB.GraphApiVersion return v2.6, then i upgraded SDK to 7.11.1, it still returns v2.6,
then i tried changing "Upgrade API Version" in facebook app console advance setting, nothing changes.
Am i doing it wrong, plz help.

**Comment by tommimarkus** [comment]
Looking at https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Constants.cs, yes the plugin is still using v2.6

**Comment by num0n1** [comment]
@tommimarkus , thanks

**Comment by tommimarkus** [comment]
It would be nice if the official plugin would support versions that aren't being deprecated, I agree

**Comment by KylinChang** [comment]
The latest UnitySDK would fetch the latest FBAndroidSDK and the Graph API version should be the latest one.
