### ISSUE TITLE
Graph API 2.6 will be deprecated on July 13

### ISSUE THREAD

**Issue by Claytonious** [facebook/facebook-sdk-for-unity#174]
... but the latest version of the Facebook Unity SDK still reports itself as graph API 2.6.

Will there be a new release of the facebook unity sdk prior to this date?

Will the current release continue to work after July 13 if we make changes to what we're requesting according to the API Upgrade Tool?

Anything we should know before this date arrives?

Thanks!

**Comment by doornboz** [comment]
We got the exact same issue.

We're always updating our Facebook SDK when stable release is there, but now we noticed that Graph API doesn't seem to be updated in a long time inside the Facebook Unity SDK.

Will it be possible soon to update the Facebook Unity SDK to the newest Graph API?

**Comment by mcginley561** [comment]
It seems that this is the intended behavior. The Unity SDK will by default target the lowest version of the API that your Facebook App is capable of making API calls to. Once your app is no longer eligible for v2.6 of the Graph API, all calls will then default to v2.7.

See bug posted on the developer forum: https://developers.facebook.com/support/bugs/893316920852369/?disable_redirect=0

**Comment by doornboz** [comment]
Thanks @mcginley561! Great information already, we didn't found this before.
