### ISSUE TITLE
Where is facebooks manifest?

### ISSUE THREAD

**Issue by 2rusbekov** [facebook/facebook-sdk-for-unity#175]
Updated sdk to 7.13.0 and got issue on android manifests merge. But there is no manifest in fb folder and none of mine manifests contains FacebookActivity. 

> \Temp\StagingArea\AndroidManifest-main.xml:32:13-72 Error:
> 	Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:32:13-72
> 	is also present at AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme).
> 	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest-main.xml:29:9-32:75 to override.
> 
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by eladleb** [comment]
I'm having the same issue. iOS builds fine though :(

**Comment by 2rusbekov** [comment]
Fixed issue:
Created FBDependencies.xml in Editor folder with next content

> <?xml version="1.0" encoding="utf-8"?>

<dependencies>
	<androidPackages>
		<androidPackage spec="com.android.support:appcompat-v7:27.1.1+" />
	</androidPackages>
</dependencies>
