### ISSUE TITLE
NullPointerException in FB.java Line 378

### ISSUE THREAD

**Issue by patrickpaul** [facebook/facebook-sdk-for-unity#18]
After deploying to our customers we found a decent percentage of users running into NullPointerExceptions when logging in.

Stack Trace:
com.facebook.unity.FB.getKeyHash (FB.java:378)
com.facebook.unity.FBLogin.login (FBLogin.java:92)
com.facebook.unity.FBLogin.loginWithReadPermissions (FBLogin.java:42)
com.facebook.unity.FBUnityLoginActivity.onCreate (FBUnityLoginActivity.java:40)
android.app.Activity.performCreate (Activity.java:5372)
dalvik.system.NativeStart.main (NativeStart.java)

We were able to fix locally by adding NullPointerException to the list of caught exceptions near line 378 in FB.java but this potentially hides something that should be fixed.

Thank you!

**Comment by swiese** [comment]
I think what has happened here is that the unity activity has died when you come back from login. We then try to access to get the keyhash and crash. I'll look at fixing this in the next release

https://github.com/facebook/facebook-sdk-for-unity/blob/e55c7f43ec9194af76feeca0476bdd5de7861607/facebook-android-wrapper/src/com/facebook/unity/FB.java#L378

**Comment by MixMasterRickyC** [comment]
I've done the same as Patrick and added the NullPointerException, I've not personally been able to recreate the issue but looking through the Google Play Developer Console it's our number one crash issue.

I've subscribe to this issue but is there an eta on the next version? 
Thanks.

**Comment by xataxxx** [comment]
I see a lot of these as well for my users...

**Comment by xataxxx** [comment]
Is this fixed now? I see in the 7.5.0 changelog there's a Fixed: NPE on Android when Unity activity was killed during login flow.

**Comment by Nitin-Joshi-perk** [comment]
Hope this is fixed in with V7.5

**Comment by swiese** [comment]
This should have been fixed in 7.5.0

**Comment by TanveerakaRocker** [comment]
@swiese , we are also seeing this issue in production release, We are using FB SDK 7.4.0, is this fixed in 7.5.0?
