### ISSUE TITLE
Facebook SDK depends on 25.3.1 Android support libraries, when it will be updated?

### ISSUE THREAD

**Issue by vladlarin** [facebook/facebook-sdk-for-unity#180]
Hi! 
When tried to update PushWoosh push notification service for Android 8 support it appeared that they depend on conflicting Android support libraries (25.3.1 vs 27.x.x versions). Does it planned to update this libraries in Facebook SDK and if not how can we workaround that issue? 

Thanks!

**Comment by izibazi** [comment]
I have the same issue.
When I imported Firebase 5.2.1 and Facebook SDK 7.9.0, happened 64k issue.

**Comment by vladlarin** [comment]
So used suggestions from #125 and it helped a lot, also changed 25.3.1 to 27.0.2 and added android.arch.* dependencies into custom unity fb sdk build so they automatically fetched by jar resolver.
