### ISSUE TITLE
How to toggle AutoLogAppEventsEnabled programmatically

### ISSUE THREAD

**Issue by kiyotg** [facebook/facebook-sdk-for-unity#182]
I have to be able to toggle sending events or not for GDPR.

In iOS or Android native apps, they set "AutoLogAppEventsEnabled" false in metadata and set it true programmatically after they get users' consent.
In Facebook's official guide, they recommend to do so.
iOS: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events
Android: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events

I can change "AutoLogAppEventsEnabled" false in metadata with UnityEditor.
But I cannot find to how to toggle "AutoLogAppEventsEnabled" programmatically.

How can I toggle "AutoLogAppEventsEnabled" with Unity SDK?
Or should I use something alternative (e.g. FB.LimitAppEventUsage)?

**Comment by KylinChang** [comment]
Hey @kiyotg , the latest Unity SDK provides API to programmatically turn on/off App Events flags, please refer to https://developers.facebook.com/docs/app-events/unity/ for more details.
