### ISSUE TITLE
Is there a safe way to check if the SDK has be loaded properly?

### ISSUE THREAD

**Issue by armnotstrong** [facebook/facebook-sdk-for-unity#185]
Hi, we are using this Facebook SDK because we are promoting our games on Facebook, according to the guide we should log event to facebook using this SDK.

We are using the sample code found here:
[check the example](https://developers.facebook.com/docs/unity/examples/)

But if we call FB.LogAppEvent() right after the `Awake` in the `Start` method, there will be an exception 

`NullReferenceException: Facebook object is not yet loaded.  Did you call FB.Init()?`

complaining that Facebook object is not loaded, but if we choose to fire that event later, things will be fine:

  ```
 IEnumerator waitToLogFBEvent()
    {
        yield return new WaitForSeconds(10f);
        Debug.Log("now will log fb event");
        FB.LogAppEvent("start"); // no error here
    }
 void Start (){
      StartCoroutine(waitToLogFBEvent()); 
      FB.LogAppEvent("start"); // error here
   }
```

So it seems your SDK will take time to be loaded? and so what's the time?

This is a really big issue because an exception could interrupt all executions after it. And we are shocked that this is neither documented or fixed.

**Comment by Andreyul** [comment]
https://developers.facebook.com/docs/unity/examples/
**Initialize the SDK**
Call `FB.Init(InitCallback, OnHideUnity);` in `Awake`
> what's the time?

SDK is loaded when it calls `InitCallback` callback.

```
private void InitCallback ()
{
    if (FB.IsInitialized) {
        FB.ActivateApp();

        // Continue with Facebook SDK
        // ... log events, etc
        FB.LogAppEvent("start");
    }
}
