### ISSUE TITLE
IOS - Unable to find the file for the assembly named 'Facebook.Unity.Canvas, 

### ISSUE THREAD

**Issue by davisan** [facebook/facebook-sdk-for-unity#189]
Hi! I updated the Facebook SDK to version 7.13 and now I'm having a problem when building for IOS with Unity 2017.2.0f3 on OSX.

System.ArgumentException: Unable to find the file for the assembly named 'Facebook.Unity.Canvas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' specified in link file ‘/…/link.xml'. Should this assembly be in the project? Use the 'ignoreIfMissing="1"' attribute if this assembly may not always exist. ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Facebook.Unity.Canvas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Any ideas? Thanks!

**Comment by STARasGAMES** [comment]
Hi! Did you find a solution?

**Comment by KylinChang** [comment]
Hi @davisan , @STARasGAMES , the issue should be fixed in the latest Unity SDK v7.17.2. Close the issue and feel free to re-open it if you still have questions.
