### ISSUE TITLE
iOS: Facebook dialogs do not open when wrapped in (multiple) callbacks

### ISSUE THREAD

**Issue by derFunk** [facebook/facebook-sdk-for-unity#19]
Hi there,

I'm seeing the issue that the `FB.Mobile.AppInvite` dialog does not get displayed when it's called from within other callbacks / threads.

I'm currently on Unity 5.4.0 beta 3 and have tested with iOS 9.0.0 and 9.2.1.

When opening the `FB.Mobile.AppInvite` dialog directly from the Unity main thread it opens as expected.

When it's not opening, I'm seeing this warning in the iOS console:
```Warning: Attempt to present <FBSDKContainerViewController: 0x1650025f0> on <FBSDKContainerViewController: 0x1669a3930> whose view is not in the window hierarchy!```

That's a code example of what I'm doing:

```
# default FB login call happens after the app starts.
# this will be executed if the user is not logged in to Facebook and if she
# wants to share a URL:

FB.LogInWithReadPermissions(new List<string>() { "public_profile", "email", "user_friends" }, (result =>
        {
            if (!FB.IsLoggedIn)
            {
                return;
            }
            
            FB.Mobile.AppInvite(myAppUri, myAppImageUri);
        });
```

I havn't tested but I'm expecting the same would happen to the ShareLink dialog.

Any ideas what could be wrong here?

**Comment by swiese** [comment]
Please report bugs to 
https://developers.facebook.com/bugs/
