### ISSUE TITLE
FB.AcivateApp() don't show up in dashboard ( other app events are showing correctly )

### ISSUE THREAD

**Issue by slender9168** [facebook/facebook-sdk-for-unity#199]
Hi,
The app launch events (FB.ActivateApp() are not showing in facebook analytics events ( in the debug events console ), while other events are showing fine 

- using latest facebook sdk ( 7.14.0 )
- unity 2017.1.5f1
- code of FB.ActivateApp() is copied from sdk online docs ( it initialized the sdk then calls FB.ActivateApp()
- other events are fired using the example scenes that come with the sdk
- tested on iphone 6    ios 12.1

**Comment by AlekseySimonenko** [comment]
We have the same problem only on ios after update on new sdk (on previus sdk all works correct)

Facebook unity sdk 7.14.0
Unity 2018.2.8f1

On android the same event work correct

**Comment by slender9168** [comment]
@AlekseySimonenko 
I've filed a bug report,  you can vote it up so the devs fix the issue faster

https://developers.facebook.com/support/bugs/2055907901134508/?disable_redirect=0

Thanks !

**Comment by slender9168** [comment]
@umutg4d  here is a report of the bug 

https://developers.facebook.com/support/bugs/2055907901134508/?disable_redirect=0

but I recommend just going to the older version of the facebook sdk for bug free quick solution ( that's what i did )

**Comment by umutg4d** [comment]
> @umutg4d here is a report of the bug
> 
> https://developers.facebook.com/support/bugs/2055907901134508/?disable_redirect=0
> 
> but I recommend just going to the older version of the facebook sdk for bug free quick solution ( that's what i did )
> 
> ( although they state it's not a bug & you can get the events by enabling auto logging )

Ok,thanks

**Comment by nmbileg** [comment]
Hey guys I'm having a same problem here, ActivateApp() seems to be not working even though I've set auto logging true. I'm building on iOS, I'm scratching my head all day, pls help...

**Comment by fire67** [comment]
A new version is available 7.15.0, does this fix the issue ? I am still not seeing any install event registered in the dashboard.
Any workaround available ?
Thanks.

**Comment by nmbileg** [comment]
Hello. yes as far as i'm concerned the new update did fix the issue. You
can check the phone console to check if the application is sending events
to facebook. And good luck!
