### ISSUE TITLE
FBSDKShareKit/FBSDKShareKit.h file not found when building for ios

### ISSUE THREAD

**Issue by Marreck** [facebook/facebook-sdk-for-unity#2]
When I create a new empty 2d project with Unity3d 5.2.1f1 and import the 7.1 sdk and then build for ios I get the error "FBSDKShareKit/FBSDKShareKit.h' file not found" in xcode 7.0.

I am at a loss on how to solve this. Any ideas?

**Comment by swiese** [comment]
Did you download the package from the developer site or did you build it from the source code in this project?

https://origincache.facebook.com/developers/resources/?id=facebook-unity-sdk-7.1.0.unitypackage

**Comment by Marreck** [comment]
I got the package from link you posted.

**Comment by swiese** [comment]
I haven't been able to repo your issue. Can you make sure the import worked successfully. You should see the following in the plugin folder 

![Plugin folder structure]
(http://i.imgur.com/2KgDyvd.png)

**Comment by Marreck** [comment]
That is what is shown here. I have attached a screenshot. I have also attached a screenshot of the files that were build.

![dir](https://cloud.githubusercontent.com/assets/8293672/10189153/df2ae5d0-6764-11e5-852c-f69c3d92d249.PNG)

![osx](https://cloud.githubusercontent.com/assets/8293672/10189160/e52ea44e-6764-11e5-90db-ff3f249c6082.PNG)

![osx2](https://cloud.githubusercontent.com/assets/8293672/10189161/e6d02dc2-6764-11e5-8a74-51b5ad0be18f.PNG)

**Comment by Marreck** [comment]
I have found the problem. For some reason the Framework Search Path was set wrong. Instead of $(inherited) $(PROJECT_DIR)/Frameworks\Plugins/iOS/Facebook it should be $(inherited) $(PROJECT_DIR)/Frameworks/Plugins/iOS/Facebook

**Comment by swiese** [comment]
Nice find!

Unity does the picking up of all frameworks in the Plugins/iOS folder and adding them to the xcode with the correct search path. Odd though that they only messed up one slash when adding the path.

**Comment by Marreck** [comment]
Also weird that I didn't encounter it with other frameworks. I'll report it as a bug with Unity.

Thanks for the help!

**Comment by orcunnisli** [comment]
I'm using Unity 5.3.5f1, Facebook SDK 7.6 (also tried 7.2) and XCode 6.  This issue is  8 months old but it is still occurring with new versions of Unity and Facebook. 

I can create XCode project from Unity but when I try to build the XCode Project, it gives the same error above. I am using an automated build tool and so I can't fix it on XCode on each build, I need a permanent solution inside Unity. Is there any?

Also In my case, fixing the slash and rebuilding didn't fixed my problem. Is says other Facebook h files are not found.

**Comment by mosky17** [comment]
same here orcunnisli, did you manage to resolve?

**Comment by NijaahnandhRV** [comment]
Still I get this issue, Can anyone help me with this issue please

I have added my FacebookSDKs-iOS-4.37.0 framework in document folder and I have also added in my project.

![screen shot 2018-10-11 at 5 33 53 pm](https://user-images.githubusercontent.com/37614736/46802808-1a8eb900-cd7c-11e8-902c-ce5bc035e2e3.png)

In libraries -> RCTFBSDK.xcodeproj -> Build Settings -> Header Search Paths

![screen shot 2018-10-11 at 5 34 16 pm](https://user-images.githubusercontent.com/37614736/46802888-588bdd00-cd7c-11e8-8693-8aa7c7477eb7.png)


In libraries -> RCTFBSDK.xcodeproj -> Build Settings -> Framework Search Paths

![screen shot 2018-10-11 at 5 38 12 pm](https://user-images.githubusercontent.com/37614736/46802936-76594200-cd7c-11e8-9ffe-1c3382511680.png)

**Comment by khayreddinebiada** [comment]
I tried this commands It's work and know I can build. you need open your terminal and go to you XCode Folder then excite this commands lines. If it now work try repeat second time.

>pod 'FBSDKShareKit'
>pod install

**Comment by glaksmono** [comment]
Hey guys, what is the official solution for this?
