### ISSUE TITLE
Facebook POST not working but ShareLink does.

### ISSUE THREAD

**Issue by loftyy** [facebook/facebook-sdk-for-unity#20]
Hey, 

I have two plugins which are clashing (I think).
SDKBOX.IAP is an in app purchase plugin for google play products which works completely fine until I try to use FB.API to post a users highscore to his facebook account/my game. 

I tried it with the Permission: user_friends and I got the 403 FORBIDEN Error (which is normal).
After adding that permission, my app just crashes directly and shows this error in logcat:

I/Unity   (27014): SDKBOX Initialized.
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
I/Unity   (27014): Dispatching callback method: onInitialized
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
I/Unity   (27014): Using Facebook Unity SDK v7.3.0 with FBAndroidSDK/4.8.2
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
I/Unity   (27014): PurchaseHandler.onInitialized False
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
I/Unity   (27014): Dispatching callback method: onProductRequestSuccess
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
E/Unity   (27014): Trying to add Price (UnityEngine.UI.Text) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
E/Unity   (27014):
E/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
E/Unity   (27014):
I/Unity   (27014): Logged in
I/Unity   (27014):
I/Unity   (27014): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (27014):
I/Unity   (27014): AndroidJavaException: java.lang.NoSuchMethodError: no static method "Lcom/sdkbox/plugin/SDKBox;.onPause(Lcom.sdkbox.activity.CustomActivity;)V"
I/Unity   (27014):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
I/Unity   (27014):   at UnityEngine.AndroidJNISafe.GetStaticMethodID (IntPtr clazz, System.String name, System.String sig) [0x00000] in <filename unknown>:0
I/Unity   (27014):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0
I/Unity   (27014):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0
I/Unity   (27014):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0
I/Unity   (27014):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unkn

Here is the script: http://pastebin.com/6Tq5nPJX
FBLogin() is called when the button is pressed.
The issue is probably coming from APIPost().

Anyways to solve this? I'm trying to make a leaderboard from facebook friends.

**Comment by swiese** [comment]
Please report bugs to 
https://developers.facebook.com/bugs

**Comment by loftyy** [comment]
Posted: https://developers.facebook.com/bugs/950723438375880/
