### ISSUE TITLE
Can't login on iOS Unity 2018.2.1f

### ISSUE THREAD

**Issue by otacon717** [facebook/facebook-sdk-for-unity#206]
public void Login()
{
            FB.LogInWithReadPermissions(new List<string>() { "public_profile", "email"}, this.AuthCallback);
 }

Unity 2018.2.1f
Facebook SDK v7.15.0

Result:
When facebook app installed
Facebook.Unity.LoginResult
LoginResult:
	Error: Unknown error building URL.
	RawResult: {"error":"Unknown error building URL.","callback_id":"2"}
	Cancelled: False
LoginResult:
	AccessToken: null

Facebook.Unity.CallbackManager:TryCallCallback(Object, IResult)
Facebook.Unity.CallbackManager:CallCallback(Object, IResult)
Facebook.Unity.CallbackManager:OnFacebookResponse(IInternalResult)

When facebook app not installed
2018-12-25 18:53:51.060910+0800  -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-12-25 18:53:51.070956+0800  -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
Facebook.Unity.LoginResult
LoginResult:
	Error: Unknown error building URL.
	RawResult: {"error":"Unknown error building URL.","callback_id":"2"}
	Cancelled: False
LoginResult:
	AccessToken: null

Facebook.Unity.CallbackManager:TryCallCallback(Object, IResult)
Facebook.Unity.CallbackManager:CallCallback(Object, IResult)
Facebook.Unity.CallbackManager:OnFacebookResponse(IInternalResult)

**Comment by viktor-nedilko** [comment]
Hi, looks like this related to [fb ios sdk bug](https://github.com/facebook/facebook-objc-sdk/commit/fe67bdb3f72a2e69422b2f609bc871c1dba2005a)
Hope fix this soon

**Comment by devauk** [comment]
In case you are using the FB plugin version 7.15 try version downgrade to 7.14.1. v7.15 uses Facebook iOS SDK to version 4.39.0 there is a bug that causes this error.  Downgrading plugin version to 7.14.1 (uses Facebook iOS SDK to version 4.38.1) will help you to solve this problem.

**Comment by KylinChang** [comment]
Hey @otacon717  @viktor-nedilko, FB Unity SDK v7.15.1 is released and the issue is fixed.
