### ISSUE TITLE
Error with FB.ShareLink() in SDK 7.15.1

### ISSUE THREAD

**Issue by jmzavala** [facebook/facebook-sdk-for-unity#218]
I'm using SDK 7.15.1 and when Intry to share a link with the following example code :
```
 try
        {
            FB.ShareLink(
                new Uri("https://developers.facebook.com/"),
                "Link Share",
                "Look I'm sharing a link",
                new Uri("http://i.imgur.com/j4M7vCO.jpg"),
                callback: this.HandleResult);
        }
catch (Exception e){
...
}
```
In the game I am logged in Facebook and when I press the button to share the link,  the application fail and crashes.  The log in the Xcode debug is:

2019-01-29 23:09:58.924806-0300 mygame[14549:5324203] +[NSError fbRequiredArgumentErrorWithDomain:name:message:]: unrecognized selector sent to class 0x1fe41ef80
2019-01-29 23:09:59.033071-0300 mygame[14549:5324203] Uncaught exception: NSInvalidArgumentException: +[NSError fbRequiredArgumentErrorWithDomain:name:message:]: unrecognized selector sent to class 0x1fe41ef80
(
	0   CoreFoundation                      0x00000001c44c0edc <redacted> + 252
	1   libobjc.A.dylib                     0x00000001c3691a40 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001c43deccc <redacted> + 0
	3   CoreFoundation                      0x00000001c44c67dc <redacted> + 1412
	4   CoreFoundation                      0x00000001c44c848c _CF_forwarding_prep_0 + 92
	5   mygame                           0x000000010396dcc4 -[FBSDKShareDialog _showShareSheetWithCanShowError:validationError:] + 1152
	6   mygame                           0x000000010396b368 -[FBSDKShareDialog _showAutomatic:] + 88
	7   mygame                           0x000000010396ab30 -[FBSDKShareDialog show] + 140
	8   mygame                           0x0000000102e808e4 -[FBUnityInterface shareContentWithRequestId:shareContent:dialogMode:] + 280
	9   mygame                           0x0000000102e804ac -[FBUnityInterface shareLinkWithRequestId:contentURL:contentTitle:contentDescription:photoURL:] + 216
	10  mygame                           0x0000000102e81288 IOSFBShareLink + 104
	11  mygame                           0x0000000103aa42f8 IOSWrapper_IOSFBShareLink_m3571816570 + 108
	12  mygame                           0x0000000103a3ad8c FacebookController_FacebookShare_m3530562870 + 280
	13  mygame                           0x000000010411f050 UnityEvent_Invoke_m3065672636 + 380
	14  mygame                           0x00000001044ac8ac

**Comment by KylinChang** [comment]
Hey @jmzavala , I think this issue is similar to #208 , can you add the -ObjC flag in the exported xcode project to see whether it can fix the issue?

**Comment by TWBestATM** [comment]
are you fix that?

**Comment by jmzavala** [comment]
Yes, I only added the -ObjC flag as recommend in the issue #208

**Comment by KylinChang** [comment]
Hey @jmzavala , can you try v7.17.2, the latest Unity SDK fetches the latest FB iOS SDK and the linking issue should be addressed in the latest FB iOS SDK
