### ISSUE TITLE
AudienceNetwork SDK - bug - InterstitialAd.isLoaded is false

### ISSUE THREAD

**Issue by BTooLs** [facebook/facebook-sdk-for-unity#22]
I couldn't find the Ads SDK public repository so I will post the bug here.

AudienceNetwork Unity SDK 4.11.0
Unity 5.3.4
Platform; Android
Bug:
InterstitialAd.IsValid is always false, even if is loaded.

The function "loadAdFromData" is only called from the iOS code, and not for Android.

**Comment by yantian001** [comment]
Yes , I also encounter this bugs . can't show interstitial on android .

**Comment by yantian001** [comment]
@BTooLs did you fix this bug?

**Comment by BTooLs** [comment]
I just ignore the flag, and show interstitial after "InterstitialAdDidLoad".

**Comment by yantian001** [comment]
Hi , 
which sdk version you used , i download the latest version ,when i call show interstitial after InterstitialDidLoad , No ad shows .. i used unity 5.3.5f1 . thanks

**Comment by swiese** [comment]
This is for the FB unity sdk. The audience network sdk is not included in this repo. 
Report bugs to https://developers.facebook.com/bugs
