### ISSUE TITLE
ReflectionTypeLoadException thrown on startup with new Unity 2018.3.7f1

### ISSUE THREAD

**Issue by NumaNumaNuma** [facebook/facebook-sdk-for-unity#224]
As soon as I hit play the UnityFacebookSDKPlugin game object (EditorFacebookGameObject script) throws this exception:

`ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Facebook.Unity.CodelessIAPAutoLog.FindTypeInAssemblies (System.String typeName, System.String nameSpace) (at <8c4c3b91cd24414db7bdbc53fc97f955>:0)
Facebook.Unity.CodelessIAPAutoLog.FindObjectsOfTypeByName (System.String typeName, System.String nameSpace) (at <8c4c3b91cd24414db7bdbc53fc97f955>:0)
Facebook.Unity.CodelessIAPAutoLog.addListenerToIAPButtons (System.Object listenerObject) (at <8c4c3b91cd24414db7bdbc53fc97f955>:0)
Facebook.Unity.Editor.EditorFacebookGameObject.OnAwake () (at <8c4c3b91cd24414db7bdbc53fc97f955>:0)
Facebook.Unity.FacebookGameObject.Awake () (at <8c4c3b91cd24414db7bdbc53fc97f955>:0)
UnityEngine.GameObject:AddComponent()
Facebook.Unity.ComponentFactory:GetComponent(IfNotExist)
Facebook.Unity.Editor.EditorFacebookLoader:get_FBGameObject()
Facebook.Unity.CompiledFacebookLoader:Start()
`

This only happens on the latest version of Unity 2018.3.7f1
Thanks

**Comment by NumaNumaNuma** [comment]
This is still happening  with any new version of Unity, could you put a try catch around it?
`try {
    // try get types
} catch(ReflectionTypeLoadException ex) {
    types = ex.Types.Where(t => t != null);
}`

**Comment by NumaNumaNuma** [comment]
Fixed in Unity 2018.3.12f1

**Comment by toxikman** [comment]
I'm getting this with Unity 2018.4.24f1 LTS and Facebook Unity SDK 7.18.1 while running the game in the Unity Editor. Happens upon Facebook SDK Init().

**Comment by NumaNumaNuma** [comment]
Hi, you should probably make a new issue and link to this one, it's unlikely anyone will check it as it is closed.
