### ISSUE TITLE
SDK can't be downloaded from web site & SDK won't compile

### ISSUE THREAD

**Issue by mihailogazda** [facebook/facebook-sdk-for-unity#225]
The downloads page doesnt work at all..

Try downloading any of the SDKs:
https://developers.facebook.com/docs/unity/change-log

Direct link is 
https://origincache.facebook.com/developers/resources/?id=facebook-unity-sdk-7.15.1.zip

**Comment by bundy2k6** [comment]
Same issue here! If anyone has any ideas it'd be much appreciated!

**Comment by mihailogazda** [comment]
Additionally build instructions in Readme are incorrect. I run the setup script to start the build, but it fails immediately.. FB didn't have a successful SDK release in years now..

![image](https://user-images.githubusercontent.com/2773099/54282192-634cd700-4593-11e9-8f42-e0c07bbbe32f.png)

**Comment by mihailogazda** [comment]
Not sure if build scripts are sorted but the download links do work.
