### ISSUE TITLE
Upgrading firebase 6.0.0 and google GPGS cause error in AndroidSupportLibraryResolver

### ISSUE THREAD

**Issue by Thaina** [facebook/facebook-sdk-for-unity#235]
Today I have upgrade firebase SDK in unity. There was some error but after update many other library such as GPGS. There was one last error that come from facebook and updating facebook SDK doen not remove this error

```
System.NullReferenceException: Object reference not set to an instance of an object
  at Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x00054] in Z:\tmp\tmp.7eOCFUaXh7\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:506 
  at Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x00000] in Z:\tmp\tmp.7eOCFUaXh7\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:481 
  at Facebook.Unity.Editor.AndroidSupportLibraryResolver.setupDependencies () [0x00034] in <10e3a2e9d4094bf5b9409184a698ff5e>:0 
  at Facebook.Unity.Editor.AndroidSupportLibraryResolver..cctor () [0x00000] in <10e3a2e9d4094bf5b9409184a698ff5e>:0 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
```

**Comment by ottolb** [comment]
I'm having the exact same error after Firebase updated to PlayServicesResolver v1.2.109.0
My builds stop working, I think it's related to the resolve process. Then I manually added these libs:
`Assets/Plugins/Android/com.android.support.animated-vector-drawable-27.1.1.aar
Assets/Plugins/Android/com.android.support.appcompat-v7-27.1.1.aar
Assets/Plugins/Android/com.android.support.cardview-v7-27.1.1.aar
Assets/Plugins/Android/com.android.support.customtabs-27.1.1.aar
Assets/Plugins/Android/com.android.support.support-vector-drawable-27.1.1.aar`

Unity version 2018.3.13

**Comment by stewartmiles** [comment]
Folks, this is being tracked in https://github.com/googlesamples/unity-jar-resolver/issues/209

**Comment by stewartmiles** [comment]
This should be fixed in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.111

**Comment by ottolb** [comment]
This update fixes the issue for me.
Thanks!

**Comment by Thaina** [comment]
I think this already fixed. Thank you very much

**Comment by iceflaming** [comment]
This update fixes the issue for me also.
Thanks!

**Comment by edscodeblenders** [comment]
I'm having the same issue with PlayServicesResolver v1.2.111. Any other idea on how to fix it?

**Comment by Thaina** [comment]
@edscodeblenders Maybe using 1.2.112 ?

**Comment by karmataktsang** [comment]
> I'm having the exact same error after Firebase updated to PlayServicesResolver v1.2.109.0
> My builds stop working, I think it's related to the resolve process. Then I manually added these libs:
> `Assets/Plugins/Android/com.android.support.animated-vector-drawable-27.1.1.aar Assets/Plugins/Android/com.android.support.appcompat-v7-27.1.1.aar Assets/Plugins/Android/com.android.support.cardview-v7-27.1.1.aar Assets/Plugins/Android/com.android.support.customtabs-27.1.1.aar Assets/Plugins/Android/com.android.support.support-vector-drawable-27.1.1.aar`
> 
> Unity version 2018.3.13

Hello, 
Where can I download these aar files?
Thanks.

**Comment by MiniKimmy** [comment]
> I'm having the exact same error after Firebase updated to PlayServicesResolver v1.2.109.0
> My builds stop working, I think it's related to the resolve process. Then I manually added these libs:
> `Assets/Plugins/Android/com.android.support.animated-vector-drawable-27.1.1.aar Assets/Plugins/Android/com.android.support.appcompat-v7-27.1.1.aar Assets/Plugins/Android/com.android.support.cardview-v7-27.1.1.aar Assets/Plugins/Android/com.android.support.customtabs-27.1.1.aar Assets/Plugins/Android/com.android.support.support-vector-drawable-27.1.1.aar`
> 
> Unity version 2018.3.13

Hi, can you show me how can you config your `*Denpendencies.xml` with [googlesamples/unity-jar-resolver#209](https://github.com/googlesamples/unity-jar-resolver/issues/209) ?
