### ISSUE TITLE
Some conflicting dependencies were found and its crash my app

### ISSUE THREAD

**Issue by storybell** [facebook/facebook-sdk-for-unity#238]
I used unity IAP, google play game services, facebook Sdk and facebook audience network sdk

Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:appcompat-v7:25.3.1 --> com.android.support:appcompat-v7:26.1.0
com.android.support:cardview-v7:25.3.1 --> com.android.support:cardview-v7:26.1.0
com.android.support:customtabs:25.3.1 --> com.android.support:customtabs:26.1.0
com.android.support:support-v4:25.3.1 --> com.android.support:support-v4:26.1.0

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:87)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:729)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__33(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:698)
GooglePlayServices.<GradleResolution>c__AnonStorey1C:<>m__3E() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:770)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:349)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__34(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:771)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__35(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:818)
GooglePlayServices.ProgressReporter:SignalComplete() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by studentutu** [comment]
@storybell have you tried reimporting? Also, try to use some of the steps from https://github.com/facebook/facebook-sdk-for-unity/issues/237

**Comment by storybell** [comment]
I'm using unity 2017.1.1 and here how i deal with this issue.

1) delete all the plugins
2) import unity IAP
3) import google play game service without play service resolver
4) import facebook 7.15.1 sdk fully with play service resolver
5) import facebook audience network sdk
6) disable auto resolution in android setting under play service resolver
7) used manual Resolve( not Force resolve)
8) Disable any duplicate library ( if any ). In my case some of library that audience network used are duplicate, so i disable the library which is under the pluings->android ( not the one that comes with the audience network )
9) Try build and success. 
the warning doesn't comes up and its not even crash. work like a charm

**Comment by biswadeep-sarkar** [comment]
> I'm using unity 2017.1.1 and here how i deal with this issue.
> 
> 1. delete all the plugins
> 2. import unity IAP
> 3. import google play game service without play service resolver
> 4. import facebook 7.15.1 sdk fully with play service resolver
> 5. import facebook audience network sdk
> 6. disable auto resolution in android setting under play service resolver
> 7. used manual Resolve( not Force resolve)
> 8. Disable any duplicate library ( if any ). In my case some of library that audience network used are duplicate, so i disable the library which is under the pluings->android ( not the one that comes with the audience network )
> 9. Try build and success.
>    the warning doesn't comes up and its not even crash. work like a charm

How to find duplicate libraries? and how to disable them? Please help...
