### ISSUE TITLE
Error when building facebook sdk (7.16.0) on iOS with xcode 10.1

### ISSUE THREAD

**Issue by kultie** [facebook/facebook-sdk-for-unity#249]
FBUnityInterface.mm:472:47: Cannot initialize a parameter of type 'BOOL' (aka 'signed char') with an rvalue of type 'NSNumber * _Nonnull'
FBUnityInterface.mm:477:53: Cannot initialize a parameter of type 'BOOL' (aka 'signed char') with an rvalue of type 'NSNumber * _Nonnull'

**Comment by kultie** [comment]
Not sure what the NSNumber use for in these method but parsing BOOL value without NSNumber make the build succcess.

**Comment by kultie** [comment]
Building success but the codeless api return null reference when using callback from facebook interface

**Comment by ExBlacklight** [comment]
I have the exact same issue,build successful and tested it on iphone, but archive fails.

**Comment by ExBlacklight** [comment]
i didn't know what the issue was with 7.16.0 but i switched back to 7.15.1 and it was fine

**Comment by NathJt** [comment]
I have the same error using the same configuration. I have noticed that it's building in debug mode but not in release. What could go wrong ?

**Comment by yuquan0821** [comment]
I have the same error. download package in official website.please fix it. thanks

**Comment by Duobix** [comment]
The same error here. Any solutions?

**Comment by PacPalCent** [comment]
I changed this part of the code from this:

`void IOSFBAutoLogAppEventsEnabled(BOOL autoLogAppEventsEnabledID)
  {
    [FBSDKSettings setAutoLogAppEventsEnabled:[NSNumber numberWithBool:autoLogAppEventsEnabledID]];
  }

  void IOSFBAdvertiserIDCollectionEnabled(BOOL advertiserIDCollectionEnabledID)
  {
    [FBSDKSettings setAdvertiserIDCollectionEnabled:[NSNumber numberWithBool:advertiserIDCollectionEnabledID]];
  }`

to this:

`void IOSFBAutoLogAppEventsEnabled(BOOL autoLogAppEventsEnabledID)
  {
    [FBSDKSettings setAutoLogAppEventsEnabled:autoLogAppEventsEnabledID];
  }

  void IOSFBAdvertiserIDCollectionEnabled(BOOL advertiserIDCollectionEnabledID)
  {
	[FBSDKSettings setAdvertiserIDCollectionEnabled:advertiserIDCollectionEnabledID];
  }`

And it worked for me.

**Comment by tigerwng** [comment]
@PacPalCent  Thanks! Its work for me.

**Comment by KylinChang** [comment]
The issue should be fixed in v7.16.1

**Comment by Eirienen** [comment]
In debug mode still showing error, even in iPhone build
