### ISSUE TITLE
7.5 doesn't build on android

### ISSUE THREAD

**Issue by orrgal1** [facebook/facebook-sdk-for-unity#25]
just upgraded to 7.5, and now my android build is failing. attaching the editor log. 

[UnityAndroidBuildCrashWithFb7.5.log.zip](https://github.com/facebook/facebook-sdk-for-unity/files/310747/UnityAndroidBuildCrashWithFb7.5.log.zip)

7.3 builds fine on the same project. haven't tried 7.4.

**Comment by swiese** [comment]
Report bugs to https://developers.facebook.com/bugs
