### ISSUE TITLE
Can't build on ios with 7.16.0 on jenkins

### ISSUE THREAD

**Issue by ilterbilguven** [facebook/facebook-sdk-for-unity#254]
I'm using jenkins for automated builds.

After upgrading to 7.16.0, I got this error while my unity project is at the xcodebuild stage:

The following build commands failed:
	CompileC /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Unity-iPhone-fwgwxtvjjdqkdohaxxwchpuctwjo/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/FBUnityInterface.o Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

If I manually build with xcode 10.x, I don't get this error.

I downgraded to 7.15.1 and it works now.

p.s.: Because of having OneSignal in my project, I'm using "legacy build system" for building my project.

p.s.: Using Unity 2018.4.x

**Comment by KylinChang** [comment]
Hi @ilterbilguven , I think the issue should be fixed in v7.16.1 now.
