### ISSUE TITLE
Receive warning on Android/IOS about only having to do action on Android/IOS

### ISSUE THREAD

**Issue by crener** [facebook/facebook-sdk-for-unity#26]
When calling FB.ActivateApp() from the editor set to Android or IOS I get a message stating "This only needs to be called for iOS or Android." even though I'm playing from a build set to one of those platforms.

If this is intended behaviour I don't understand it surly anyone already working in editor with a supported platform doesn't need to see the message. Everyone building for multiple platforms should really be testing for each platform before building anyway and would see the message that way. 

You can easily detect what platform is currently being built for using Platform #define directives (see: http://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

 Just surround the platform dependent parts with:
# if UNITY_ANDROID || UNITY_IOS

....
# endif

that way the message will be way more relevant to people doing it rather than spam everyone using it correctly!

**Comment by swiese** [comment]
This looks like a bug when running in the editor. It does only need to be called on those products. This message will be fixed in the next release
