### ISSUE TITLE
Script Build Failure Mac

### ISSUE THREAD

**Issue by kdzapp** [facebook/facebook-sdk-for-unity#260]
```
/Users/Kyle/Desktop/facebook-sdk-for-unity-master/scripts/common.sh: line 140: /Applications/Unity/Unity.app/Contents/MacOS/Unity: No such file or directory`

FATAL: Failed to import /Users/Kyle/Desktop/facebook-sdk-for-unity-master/play-services-resolver.unitypackage 

FATAL: Failed to build the android sdk plugin
```
After running `./scripts/setup.sh`

I'm trying to rebuild because I need the latest push's fix for android deployment

**Comment by KylinChang** [comment]
Hi @kdzapp , from the output, it seems that you don't install Unity or you don't install Unity by default path. Actually we will release a new version this week.

**Comment by kdzapp** [comment]
Well I of course have Unity installed because otherwise building a package for unity would be pointless. I haven't altered the path, I've installed with the Unity Hub though, and so you might want to think about how you can accommodate the path for that installation method.

**Comment by Snowblaze** [comment]
@kdzapp You should change UNITY_PATH in common.sh to something like this "/Applications/Unity/Hub/Editor/2019.1.0f2/Unity.app/Contents/MacOS/Unity", but with your installed version. But either way you will have a couple other errors, so feel free to ask.

**Comment by Snowblaze** [comment]
As you can have multiple versions of Unity installed you should change the path yourself, otherwise there is no way to determine which one the person building the package wants.

**Comment by kdzapp** [comment]
got it closing this then
