### ISSUE TITLE
v7.16 iOS Build Failure due to duplicate symbols in FBSDKCoreKit.framework

### ISSUE THREAD

**Issue by jzhudev** [facebook/facebook-sdk-for-unity#261]
When build exported XCode 10.2.1 project from Unity 2018.2, there is many similar build errors like: `duplicate symbol _OBJC_CLASS_$_FBSDKGraphRequestPiggybackManager in:
    /Assets/../ExportProjects/IOS/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKGraphRequestPiggybackManager.o)
    /ExportProjects/IOS/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKGraphRequestPiggybackManager.o)`

I found that if I remove "-force_load" and the following FBSDKCoreKit path under Other Linker Flags, it could build with no problems. 

v7.15 has no such issue. 

related issue #208

**Comment by keysguy** [comment]
I found too, but in my project, the 7.16.0 is ok, the error occurred in 7.16.1.
It's caused by the modify of FixupFiles.cs, It's change from:
7.16.0:
            string corekitPath = Path.Combine(path, "Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/FBSDKCoreKit");
            proj.AddBuildProperty(targetGUID, "OTHER_LDFLAGS", "-force_load " + corekitPath);

to :
7.16.1:
            proj.AddBuildProperty(targetGUID, "OTHER_LDFLAGS", "-all_load");

This will make all my ".a" files linked into the binary file, and if two different lib file point to same target, it's will be error!

**Comment by KylinChang** [comment]
Hi @keysguy , you can change to use -force_load flag instead
