### ISSUE TITLE
v7.17.0 dll platforms setting error

### ISSUE THREAD

**Issue by laijingfeng** [facebook/facebook-sdk-for-unity#266]
Facebook.Unity.Android.dll
Facebook.Unity.iOS.dll
4 dlls in total, all set to 'Any Platform'

**Comment by NicholasSheehan** [comment]
![image](https://user-images.githubusercontent.com/13064027/60343339-ad739000-99ab-11e9-9396-018b3e7bac34.png)
Image for reference, have the same issue

**Comment by OniTheC4t** [comment]
Flag the .dll in the Assets/FacebookSDK/Plugins/Android as Android and  Assets/FacebookSDK/Plugins/IOS as IOS should solve 
<img width="1448" alt="Schermata 2019-06-28 alle 16 02 48" src="https://user-images.githubusercontent.com/7911705/60347707-44e1de80-99be-11e9-8166-c5e86d1d6be4.png">

**Comment by kdzapp** [comment]
Why are there two dlls for each platform?

**Comment by oscargoldman** [comment]
I can't get this version to compile even in an empty blank project. Why are there duplicate .dll's? Deleting one set of them, from the appropriate folders causes build errors as well. This version seems dead out the door....

**Comment by nitzanwilnai** [comment]
I fixed it by deleting the android dll from the iOS folder, and the iOS dll from the Android folder.

**Comment by laijingfeng** [comment]
@OniTheC4t right
