### ISSUE TITLE
Random Crash on android device when update to 7.6.0

### ISSUE THREAD

**Issue by nhnpro** [facebook/facebook-sdk-for-unity#27]
I've just updated fb sdk to 7.6.0, and random crash occured more often when i launch app (or during app running).
I'm using unity 5.1.4f

 Here is some log crash:

---- LOG CRASH ----

 W/ClassFailureStapler(10802): failed to install class failure stapler; proceeding
W/ClassFailureStapler(10802): java.lang.RuntimeException: could not hook fn dvmInitClass: control flow in TBB/TBH unpredictable
W/ClassFailureStapler(10802):   at com.facebook.common.dextricks.DalvikInternals.setClassInitFailureHook(Native Method)
W/ClassFailureStapler(10802):   at com.facebook.common.dextricks.ClassFailureStapler.install(web_view_number:31)
W/ClassFailureStapler(10802):   at com.facebook.common.dextricks.ClassFailureStapler.tryInstall(web_view_number:39)
W/ClassFailureStapler(10802):   at com.facebook.katana.app.FacebookApplication.c(}:218)
W/ClassFailureStapler(10802):   at com.facebook.base.app.DelegatingApplication.attachBaseContext(|NO:113)
W/ClassFailureStapler(10802):   at android.app.Application.attach(Application.java:197)
W/ClassFailureStapler(10802):   at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
W/ClassFailureStapler(10802):   at android.app.Instrumentation.newApplication(Instrumentation.java:992)
W/ClassFailureStapler(10802):   at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
W/ClassFailureStapler(10802):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
W/ClassFailureStapler(10802):   at android.app.ActivityThread.access$1400(ActivityThread.java:159)
W/ClassFailureStapler(10802):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
W/ClassFailureStapler(10802):   at android.os.Handler.dispatchMessage(Handler.java:99)
W/ClassFailureStapler(10802):   at android.os.Looper.loop(Looper.java:176)
W/ClassFailureStapler(10802):   at android.app.ActivityThread.main(ActivityThread.java:5419)
W/ClassFailureStapler(10802):   at java.lang.reflect.Method.invokeNative(Native Method)
W/ClassFailureStapler(10802):   at java.lang.reflect.Method.invoke(Method.java:525)
W/ClassFailureStapler(10802):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
W/ClassFailureStapler(10802):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
W/ClassFailureStapler(10802):   at dalvik.system.NativeStart.main(Native Method)

W/AppStateLogger(10802): registerAppStateLoggerStreamWithBreakpad failed
W/AppStateLogger(10802): java.lang.RuntimeException: could not find registerCustomStreamWithBreakpad
W/AppStateLogger(10802):        at com.facebook.analytics.appstatelogger.AppStateLogger.registerStreamWithBreakpad(Native Method)
W/AppStateLogger(10802):        at com.facebook.analytics.appstatelogger.AppStateLogger.h(when:230)
W/AppStateLogger(10802):        at com.facebook.analytics.appstatelogger.AppStateLogger.d(when:216)
W/AppStateLogger(10802):        at com.facebook.katana.app.FacebookApplication.c(}:204)
W/AppStateLogger(10802):        at com.facebook.base.app.DelegatingApplication.attachBaseContext(|NO:113)
W/AppStateLogger(10802):        at android.app.Application.attach(Application.java:197)
W/AppStateLogger(10802):        at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
W/AppStateLogger(10802):        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
W/AppStateLogger(10802):        at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
W/AppStateLogger(10802):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
W/AppStateLogger(10802):        at android.app.ActivityThread.access$1400(ActivityThread.java:159)
W/AppStateLogger(10802):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
W/AppStateLogger(10802):        at android.os.Handler.dispatchMessage(Handler.java:99)
W/AppStateLogger(10802):        at android.os.Looper.loop(Looper.java:176)
W/AppStateLogger(10802):        at android.app.ActivityThread.main(ActivityThread.java:5419)
W/AppStateLogger(10802):        at java.lang.reflect.Method.invokeNative(Native Method)
W/AppStateLogger(10802):        at java.lang.reflect.Method.invoke(Method.java:525)
W/AppStateLogger(10802):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
W/AppStateLogger(10802):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
W/AppStateLogger(10802):        at dalvik.system.NativeStart.main(Native Method)

**Comment by swiese** [comment]
Please report bugs to 
https://developers.facebook.com/bugs
