### ISSUE TITLE
Incompatibility with Android 64 bit?

### ISSUE THREAD

**Issue by Noxalus** [facebook/facebook-sdk-for-unity#271]
Hello everyone,

I've tested the last version of the Facebook SDK for Unity (v7.1.16) and I experience a runtime issue when I compile for ARM64 with Unity (so using IL2CPP, Unity 2018.3.10f):

```
FileNotFoundException: Could not load file or assembly 'Facebook.Unity.Android' or one of its dependencies
```

I have no problem when I target ARMv7 and x86 architectures.

As Google Play store will require the uploaded APK to target ARM64 artchitecture from august 2019, I would be pretty surprise that this SDK is not compatible yet, so I think I did something wrong, but what?

Am I the only one with this issue?

**Comment by Noxalus** [comment]
I have some news with more information.
The problem is not related to architecture, but IL2CPP.
I've tried with Facebook SDK 7.12.0, 7.15.1 and 7.16.1, the problem is always here.
If I tried to import the SDK from a fresh new Unity 2018.3.1f10 project, and the issue is not there.
No issue neither if I import the SDK in my custom project instead of using it as a package (with UPM).

So my conclusion is there is something wrong when we use the Facebook SDK as a package in a project that leads to a missing DLL for Android when we compile with IL2CPP (the problem doesn't exist with Mono).

I'm still investigating, but if anyone has a solution for this, please write it here ;)

**Comment by Noxalus** [comment]
Found!

The issue is related to the `link.xml` file needed to finkd the `Facebook.Unity.Android` dependency, but as this file is in a package (and not into a `Plugins` folder), it's not taken into account during the build.

To solve this issue, I've made a pre build script that copy this file in the project's `Plugins/Android` folder, and it works!

**Comment by uchar** [comment]
@Noxalus Can  you share your buildscript please?

**Comment by sanathkukkillaya** [comment]
@uchar While converting the Google Mobile Ads package, I found that there was a similar which had been handled by a PreProcessor script. I used the same logic in this situation as well.

To fix this I created an Editor folder with an assembly def file in Assets folder and added the following script to it.
```
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

public class FBBuildPreProcessor : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("Linking FB plugins");

        const string packagesFolderPath = "Packages/com.facebook.sdk";
        const string assetsFolderPath = "Assets/FacebookSDK";
        const string linkFile = "link.xml";

        if (AssetDatabase.IsValidFolder(assetsFolderPath) &&
            File.Exists(Path.Combine(assetsFolderPath, linkFile)))
        {
            Debug.Log("FB link file exists in Assets folder.");
            return;
        }

        if (!AssetDatabase.IsValidFolder(packagesFolderPath))
        {
            StopBuildWithMessage("FB packages folder not found.");
            return;
        }
        
        AssetDatabase.CopyAsset(Path.Combine(packagesFolderPath, linkFile),
            Path.Combine(assetsFolderPath, linkFile));
            
        Debug.Log("Copied FB link file from Packages to Assets folder.");
    }
    
    private void StopBuildWithMessage(string message)
    {
        var prefix = "[FB] ";
        throw new BuildPlayerWindow.BuildMethodException(prefix + message);
    }
}

```
I then moved this Editor folder to the FB custom package. I was able to use this package in another project as well.

**Comment by sundxing** [comment]
you saved my life
