### ISSUE TITLE
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'

### ISSUE THREAD

**Issue by birdkingz** [facebook/facebook-sdk-for-unity#273]
Envrionments:
Unity 2018.4.2f1, facebook-unity-sdk-7.17 (failed on facebook-unity-sdk-7.16 too)

I really don't understand why am I seeing this error.
Currently, I have play-services integrated and I thought PlayServiceResolver suppose to resolve duplicated libraries?

Please if anyone can point out which are the duplicated files that I should be deleting.
Screenshot 1
<a href="https://ibb.co/hsVYxfK"><img src="https://i.ibb.co/hsVYxfK/Screenshot-2019-07-01-at-9-16-48-PM.png" alt="Screenshot-2019-07-01-at-9-16-48-PM" border="0"></a>

Screenshot 2
<a href="https://ibb.co/GCDwt7B"><img src="https://i.ibb.co/GCDwt7B/Screenshot-2019-07-01-at-9-17-03-PM.png" alt="Screenshot-2019-07-01-at-9-17-03-PM" border="0"></a>

I suspect there are conflicts between Android and AndroidX libraries. But how/where can I set these properties in Unity?

```
android.enableJetifier=true
android.useAndroidX=true
```

PS: I've tried https://github.com/facebook/facebook-sdk-for-unity/issues/176 suggestion by TeamSidGames. It doesn't work.

**Comment by Kendja** [comment]
Had a similar problem today, but I use unity 2019+.

Try to enable enableJetifier in Android Resolver Settings
"Assets -> GooglePlayResolver -> Android Resolver -> Settings -> Set Jetiffier On
Force Resolve."
Be sure to use the latest version of it:
https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.121
![image](https://user-images.githubusercontent.com/1694998/60447124-30127e80-9c3c-11e9-94f0-2eadcf67ed62.png)

**Comment by birdkingz** [comment]
Now I'm seeing another error
D8: Cannot fit requested classes in a single dex file (# methods: 68538 > 65536)

**Comment by praty007** [comment]
Use Multidex
Project Settings > check Custom Gradle Build > Find mainTemplate.Gradle > add into android{..defaultConfig{**multiDexEnabled true**...}}
Build and Run

**Comment by birdkingz** [comment]
But I was trying to avoid multiDex because it might break my other plugins.
Also, it might increase the file size too.
So why enabling Jetifier increases so much in terms of dex count?

**Comment by studentutu** [comment]
@praty007  it will not work,
@birdkingz  use custom proguard file from within the unity, with the following : 
[proguard-user.txt](https://github.com/facebook/facebook-sdk-for-unity/files/3349475/proguard-user.txt)

@Kendja  Jetifier will not work in this case.

**Comment by birdkingz** [comment]
Hi @studentutu,
If @Kendja Jetifier doesn't work then I will still encounter with this **transformDexArchiveWithExternalLibsDexMergerForRelease**

Only after I applied Jetifier only seeing 
**Cannot fit requested classes in a single dex file (# methods: 68538 > 65536)**

So how should I fix this?

**Comment by praty007** [comment]
@birdkingz your methods are too many to shove into a single dex.
You must, either reduce the number of methods or use multidex. (I am very new to multidex but it seems to work for me, for now.)

**Comment by birdkingz** [comment]
I've enabled proguard and now it's working now.

**Comment by Eifersuuucht** [comment]
Just raise minimum API Level for Android 6.0 'Marshmallow'
