### ISSUE TITLE
7.6 Sometimes freezes on android during login

### ISSUE THREAD

**Issue by orrgal1** [facebook/facebook-sdk-for-unity#28]
have been using plugin for a while. i think that since upgrading to 7.6 this problem started where during the login, i guess when the plugin tries to open the fb ui, the whole app just freezes. it happens sometimes, very inconsistent, but enough to be a problem. i can't see any related logs. anyone else experiencing this?

**Comment by Nitish09c** [comment]
Yeah, experiencing this since upgrading to 7.6.

**Comment by swiese** [comment]
Please report bugs to https://developers.facebook.com/bugs
