### ISSUE TITLE
Why we have ios.dll in android folder and android.dll in ios folder?

### ISSUE THREAD

**Issue by Thaina** [facebook/facebook-sdk-for-unity#283]
![image](https://user-images.githubusercontent.com/1042507/61198302-7fa87e00-a703-11e9-83b4-2d87e4b17155.png)

**Comment by Kendja** [comment]
In some other thread they mentioned that it was a mistake. You need to disable one for each platform or remove it.

![image](https://user-images.githubusercontent.com/1694998/61211113-12531800-a718-11e9-9951-59448493f9b9.png)

**Comment by Thaina** [comment]
@Kendja I have done that but it seem very like a bug in facebook package

**Comment by rcohendw** [comment]
I think the SDK requires stubbed APIs for the other platform in order to build.  Unfortunately, it ships with the platforms checks set up incorrectly, although I still run into other link problems with Bolts.

**Comment by KylinChang** [comment]
Hey all, we have corrected the platform settings in v7.17.2. @rcohendw ,  what's your link problem?

**Comment by rcohendw** [comment]
> Hey all, we have corrected the platform settings in v7.17.2. @rcohendw , what's your link problem?

It's working now for me with 7.17.2.

My Bolts link problem *might* have actually been related to Unity IAP.  Updating the FBSDK to 7.17.2 and updating IAP solved the link problem.

Thank you!
