### ISSUE TITLE
v7.17.1 Found plugins with same names

### ISSUE THREAD

**Issue by max-tu** [facebook/facebook-sdk-for-unity#286]
When I built for android, it has 2 errors, "Found plugins with same names, Assets/FacebookSDK/Plugins/Android/Facebook.Unity.IOS.dll and Assets/FacebookSDK/Plugins/iOS/Facebook.Unity.IOS.dll. Delete the one of the duplicate plugins.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()" 
![Screen Shot 2019-07-17 at 9 26 56 AM](https://user-images.githubusercontent.com/9456746/61342643-16e11300-a875-11e9-81b3-0fdc777aa6b4.png)

I use unity 2019.1.10, facebook-unity-sdk-7.17.1.unitypackage, GoogleMobileAds-v3.18.1
I found facebook-unity-sdk not use latest play-services-resolver like GoogleMobileAds.

**Comment by Apoll0** [comment]
> When I built for android, it has 2 errors, "Found plugins with same names, 
Solved by deleting iOS lib in Android folder and Android lib in iOS folder. I think it is bug )

**Comment by max-tu** [comment]
When I deleted the files have same name, it raises the other errors.

**Comment by bogdanhodorogea** [comment]
We solved it by changing the import settings to include the plugins only on their respective platforms.
Assets/FacebookSDK/Plugins/Android/Facebook.Unity.Android.dll - uncheck "Any Platform" and only check Android
Assets/FacebookSDK/Plugins/Android/Facebook.Unity.IOS.dll - uncheck "Any Platform" and only check Android
Assets/FacebookSDK/Plugins/iOS/Facebook.Unity.Android.dll - uncheck "Any Platform" and only check iOS
Assets/FacebookSDK/Plugins/iOS/Facebook.Unity.IOS.dll - uncheck "Any Platform" and only check iOS

**Comment by fmoyano** [comment]
I solved it by removing Facebook.Unity.IOS.dll from Android folder and viceversa with Facebook.Unity.Android.dll.

**Comment by CriticalForce** [comment]
This issue seems to be resolved in 7.17.2. I didn't have to do any manual tinkering.

**Comment by KylinChang** [comment]
Hey all, we have already corrected the platform settings in v7.17.2.
