### ISSUE TITLE
7.17.2 NoSuchMethodError on Android

### ISSUE THREAD

**Issue by CriticalForce** [facebook/facebook-sdk-for-unity#288]
NoSuchMethodError: no static method with name 'setIsUnity' signature '(Z)V' in class Ljava.lang.Object;
com.unity3d.player.ReflectionHelper.getMethodID(unknown Source:167)

This happens on app start, any pointers?

Unity 2018.4.1f1
FB SDK 7.17.2

**Comment by KylinChang** [comment]
Hey @CriticalForce , thanks for the report. Can you try adding `-keep class com.facebook.internal.* {*;}
`? The issue is the same as #268

**Comment by CriticalForce** [comment]
Thanks for the help, I've added it to the project and it fixed my issue.

Where should one look for the ProGuard rules related to Facebook?
I did not find this in the Unity SDK integration documentation unfortunately.

**Comment by KylinChang** [comment]
Hey @CriticalForce, we will update our integration doc for that. Thanks for the report again!
