### ISSUE TITLE
7.17.2 XCode Build error on fresh FBSDK install

### ISSUE THREAD

**Issue by happypepper** [facebook/facebook-sdk-for-unity#293]
Using Unity 2018.4.1.
I got XCode link error: `Library not found for -lBolts`

Even after deleting and reimporting version 7.17.2 of the sdk.

**Comment by happypepper** [comment]
I just tried patching the sdk with the latest commit which removed Bolts, now i am getting `library not found for -lFBSDKCoreKit`

**Comment by JimmyDeemo** [comment]
I'm not hugely familiar with the iOS side of the SDK but have you resolved the Cocopods?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/4234718/61711819-e0136d00-ad4c-11e9-9cd5-fda0868922bf.png">

**Comment by happypepper** [comment]
I clicked that button and it says `CocoaPods installation detected /Users/lawson/.gem/ruby/2.3.0/bin/pod`

Here's some warning logs that might be relevant:
```ld: warning: directory not found for option '-L/Users/lawson/Library/Developer/Xcode/DerivedData/Unity-iPhone-cvttmzniriokjmbfxzjoqcvkwtij/Build/Products/ReleaseForRunning-iphoneos/Bolts'
ld: warning: directory not found for option '-L/Users/lawson/Library/Developer/Xcode/DerivedData/Unity-iPhone-cvttmzniriokjmbfxzjoqcvkwtij/Build/Products/ReleaseForRunning-iphoneos/FBSDKCoreKit'
ld: warning: directory not found for option '-L/Users/lawson/Library/Developer/Xcode/DerivedData/Unity-iPhone-cvttmzniriokjmbfxzjoqcvkwtij/Build/Products/ReleaseForRunning-iphoneos/FBSDKLoginKit'
ld: warning: directory not found for option '-L/Users/lawson/Library/Developer/Xcode/DerivedData/Unity-iPhone-cvttmzniriokjmbfxzjoqcvkwtij/Build/Products/ReleaseForRunning-iphoneos/FBSDKShareKit'
ld: library not found for -lBolts```

**Comment by happypepper** [comment]
I tried typing `pod` in terminal and got this:
```$ pod
-bash: pod: command not found```
is that ok?

**Comment by JimmyDeemo** [comment]
Sorry. I'm afraid I don't know, I am able to build fine without these issues. I would take a look at some of the iOS library files in the Unity project. Maybe some of them haven't been selected to be included for iOS?

**Comment by happypepper** [comment]
Hmm.. there is nothing inside the `build/Release-iphoneos` folder

**Comment by happypepper** [comment]
My bad. I realized I should open the .xcworkspace file instead of .xcodeproj file.

**Comment by kamalkam** [comment]
@happypepper  how did you solved this error 
i m also having an error like this 
FBSDKCoreKit file not found 
from xcode 
do you know how can i solve it
