### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by dipyalov** [facebook/facebook-sdk-for-unity#30]
`+ (void)initialize
{
  if (self == [FBUnitySDKDelegate class]) {
    g_instances = [NSMutableArray array];
  }
}`
in FBUnitySdkDelegate.m should be written as 
`+ (void)initialize
{
  if (self == [FBUnitySDKDelegate class]) {
    g_instances = [[NSMutableArray alloc] init];
  }
}`

because call to `array` autoreleases `g_instances` and makes app crash on `complete` call

**Comment by Andreyul** [comment]
Make sure you are compiling with ARC enabled.
http://clang.llvm.org/docs/AutomaticReferenceCounting.html#objects
> If an object is declared with retainable object owner type, but without an explicit ownership qualifier, its type is implicitly adjusted to have __strong qualification.

**Comment by dipyalov** [comment]
Thank you! I've set -fobjc-arc on all *.m/*.mm files of the wrapper and it did help.
