### ISSUE TITLE
"Download the SDK" button doesn't download last version of plugin

### ISSUE THREAD

**Issue by sotrosh** [facebook/facebook-sdk-for-unity#300]
Hi,

I spent several days for resolving library conflicts of facebook sdk with firebase. 
But issue above was fixed in **7.17.2** which is last version. The problem is that when I click on "Download the SDK", it downloads previous version (**7.17.1**) but in description it says that it's **7.17.2**.

<img width="847" alt="Screen Shot 2019-07-27 at 8 16 20 PM" src="https://user-images.githubusercontent.com/1019784/62000381-05391000-b0ac-11e9-9bd8-71c49f9c3d16.png">

Would be great if you fix that. It could save a lot of time for other developers because they think they are downloading the last version.

**Comment by dreamolight** [comment]
Fixed, please let me know if you still can't download latest version.
