### ISSUE TITLE
com.facebook.FacebookSdk.publishInstallAsync crash in v7.17.0

### ISSUE THREAD

**Issue by realluhui** [facebook/facebook-sdk-for-unity#301]
when i upgrade facebook sdk from 7.15.1 to 7.17.0, it get crash report

java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2014)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1340)
com.facebook.FacebookSdk.publishInstallAsync (FacebookSdk.java:594)
com.facebook.appevents.AppEventsLoggerImpl.activateApp (AppEventsLoggerImpl.java:112)
com.facebook.appevents.AppEventsLogger.activateApp (AppEventsLogger.java:200)
com.facebook.appevents.internal.AutomaticAnalyticsLogger.logActivateAppEvent (AutomaticAnalyticsLogger.java:67)
com.facebook.internal.FetchedAppSettingsManager$1.run (FetchedAppSettingsManager.java:203)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)

in 7.17.2, the issue still exist
before 7.17.0, it's no this issue

**Comment by KylinChang** [comment]
Hi @realluhui , the issue should be fixed starting from FBAndroidSDK v5.4.0 and you can re-export your project to get the latest FBAndroidSDK to fix the issue.
