### ISSUE TITLE
Unity 2019.2 Cloud Build (2019.2 with Facebook SDK module downloaded)

### ISSUE THREAD

**Issue by studentutu** [facebook/facebook-sdk-for-unity#307]
Unity cannot compile Facebook.Unity.Settings and Facebook.Unity - because of the duplicate already exists inside the  Unity Editor!

Please, advise on what do to next - you can force unity to eat the SDK but the  Facebook.Unity.Settings and Facebook.Unity should be set to no autoreference! After that we still have errors in Editor  (Windows/Mac) - Settings does not have the correct serialized properties!

Same errors as in issues : 
https://forum.unity.com/threads/facebook-unity-settings-has-already-been-imported-error.467925/page-2

**Comment by michael-looply** [comment]
This is an issue on Unity's end - I recommend closing this ticket and monitoring the thread [here](https://forum.unity.com/threads/delete-via-shell-facebook-build-support-unity-2019-2-0f1.727052/#post-4865930). Unity Cloud Build support has made a temporary fix available if you contact them.
