### ISSUE TITLE
Get Active Build Target Error

### ISSUE THREAD

**Issue by bradkeys** [facebook/facebook-sdk-for-unity#31]
Running Unity 5.4.0 with FB SDK 7.8, I get the following error while running my project:

_get_activeBuildTarget is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'FacebookSettingsEditor'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEditor.EditorUserBuildSettings:get_activeBuildTarget()
Facebook.Unity.Editor.FacebookSettingsEditor:.ctor()_

**Comment by swiese** [comment]
You can report bugs to 
https://developers.facebook.com/bugs

**Comment by leonardseymore** [comment]
Got mine working again by right clicking on FacebookSDK and choosing Reimport

**Comment by shinriyo** [comment]
Facebook sdk always has bug
