### ISSUE TITLE
FB.LogAppEvent() cause error

### ISSUE THREAD

**Issue by pfjhetg** [facebook/facebook-sdk-for-unity#313]
`java.util.concurrent.RejectedExecutionException. Task com.facebook.internal.FetchedAppGateKeepersManager$1@b1d587 rejected from java.util.concurrent.ThreadPoolExecutor@8313cb4[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 73]
--
2 java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java.2014)
3 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java.794)
4 java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java.1340)
5 com.facebook.internal.FetchedAppGateKeepersManager.loadAppGateKeepersAsync(FetchedAppGateKeepersManager.java.76)
6 com.facebook.internal.FetchedAppGateKeepersManager.getGateKeeperForKey(FetchedAppGateKeepersManager.java.146)
7 com.facebook.appevents.AppEventsLoggerImpl.logEvent(AppEventsLoggerImpl.java.645)
8 com.facebook.appevents.AppEventsLoggerImpl.logEvent(AppEventsLoggerImpl.java.212)
9 com.facebook.appevents.AppEventsLogger.logEvent(AppEventsLogger.java.403)
10 com.facebook.unity.FB.LogAppEvent(FB.java.261)
11 com.unity3d.player.UnityPlayer.nativeRender(Native Method)
12 com.unity3d.player.UnityPlayer.c(Unknown Source)
13 com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
14 android.os.MessageQueue.next(MessageQueue.java.392)
15 android.os.Looper.loop(Looper.java.163)
16 com.unity3d.player.UnityPlayer$e.run(Unknown Source)
17 UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>.0)
18 UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>.0)
19 Facebook.Unity.Mobile.Android.AndroidFacebook.AppEventsLogEvent (System.String logEvent, System.Nullable`1[T] valueToSum, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) (at <00000000000000000000000000000000>.0)
20 TrackEvent.Event (System.String eventName) (at <00000000000000000000000000000000>.0)
21 SoldierDataService.Combine (System.String firstIdentify, System.String secondIdentify) (at <00000000000000000000000000000000>.0)
22 SoldierController.Combine () (at <00000000000000000000000000000000>.0)
23 SoldierController.MouseClickCheck () (at <00000000000000000000000000000000>.0)
24 SoldierController.Update () (at <00000000000000000000000000000000>.0)
`
FB.LogAppEvent() with only one parameter cause this error,  it not happen every time.

**Comment by KylinChang** [comment]
This is an issue in old SDK and it should be fixed in the latest version of SDK. You can integrate with the latest Unity SDK and export your project to fix the issue.
