### ISSUE TITLE
Error when building facebook sdk (7.17.2) on iOS with xcode 10.2.1

### ISSUE THREAD

**Issue by MaxSchluetz** [facebook/facebook-sdk-for-unity#316]
FBUnityInterface.mm:472:47: Cannot initialize a parameter of type 'BOOL' (aka 'signed char') with an rvalue of type 'NSNumber * _Nonnull'
FBUnityInterface.mm:477:53: Cannot initialize a parameter of type 'BOOL' (aka 'signed char') with an rvalue of type 'NSNumber * _Nonnull'

**Comment by KylinChang** [comment]
Hi @MaxSchluetz, I think the reason is that you are using old version FBiOSSDK. The solution here is you updating FBiOSSDK v5.0.0+ or manually edit FBUnityInterface.mm in Xcode
