### ISSUE TITLE
Facebook SDK 7.17.2 build failure - directory not found

### ISSUE THREAD

**Issue by Gornian** [facebook/facebook-sdk-for-unity#319]
Hi
I'm trying build my Unity project with Facebook SDK 7.17.2 ver.
Currently I have this issue

ld: warning: directory not found for option '-L/Users/xxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-botcfpbvvzdrzdbnhrvibkeevvqn/Build/Products/ReleaseForRunning-iphoneos/Bolts'
ld: warning: directory not found for option '-L/Users/xxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-botcfpbvvzdrzdbnhrvibkeevvqn/Build/Products/ReleaseForRunning-iphoneos/FBSDKCoreKit'
ld: warning: directory not found for option '-L/Users/xxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-botcfpbvvzdrzdbnhrvibkeevvqn/Build/Products/ReleaseForRunning-iphoneos/FBSDKLoginKit'
ld: warning: directory not found for option '-L/Users/xxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-botcfpbvvzdrzdbnhrvibkeevvqn/Build/Products/ReleaseForRunning-iphoneos/FBSDKShareKit'
ld: library not found for -lBolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Everything works ok with 7.16.1

MacOS 10.13.6
Xcode 10.1

Unity 2019.2.0

Should I need to download these libs or what?

**Comment by KylinChang** [comment]
Hi @Gornian , have you run the command `pod install` in your project and you should open xcworkspace.

**Comment by Gornian** [comment]
Hi @KylinChang  
Thanks a lot man. It works.
