### ISSUE TITLE
Crash on Unity Facebook SDK 7.17.2 from Crashlytic

### ISSUE THREAD

**Issue by hoangtienptit** [facebook/facebook-sdk-for-unity#329]
com.facebook.internal.FetchedAppGateKeepersManager$2.run (FetchedAppGateKeepersManager.java:154)
android.os.Handler.handleCallback (Handler.java:907)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:216)
android.app.ActivityThread.main (ActivityThread.java:7625)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)

**Comment by KylinChang** [comment]
Hi @hoangtienptit , this issue comes from FBAndroidSDKv5.5.0 and is the same as https://github.com/facebook/facebook-sdk-for-unity/issues/328. 
The solution is to re-export the android project and rebuild it with latest FBAndroidSDKv5.5.1
