### ISSUE TITLE
The FB login works fine in Unity Editor. But Show Invalid Key when running on Android Mobile

### ISSUE THREAD

**Issue by thomaspolo** [facebook/facebook-sdk-for-unity#33]
Guys as the Title Says the Issue. I have checked out everything.. Even Regenerated the Key. But Everything is fine while using the FB Login system in Unity Editor. But when i compile and Use the Apk in android mobile. the login never works. it shows invalid. please this stuff blocking me from my game launch. A Fast reply with complete details would be highly helpfull

**Comment by bblpny** [comment]
Hey thomaspolo, I'm not with Facebook but have you taken a look at the logs? The logs will state some hash value in base64, saying it does not match what is registered.

If you copy that value in the log, you can then paste that into your android settings within the developer section of your app on developer.facebook.com .

**Comment by swiese** [comment]
The editor is only a mock. You need to correctly setup your Android key hash following the guide at 
https://developers.facebook.com/docs/unity/getting-started/android
