### ISSUE TITLE
Facebook SDK v7.17.2 NullReferenceExceptions CodelessUIInteractEvent.Update()

### ISSUE THREAD

**Issue by Hilson8** [facebook/facebook-sdk-for-unity#332]
On FB SDK 7.17.2 we're still getting the same issue as #252, as that issue has been closed I am opening a new one. 

This null ref is happening on every click/tap interaction. 

Null ref within Facebook.Unity.CodelessUIInteractEvent.Update()

Using Unity 2019.1.5f1

**Comment by SozapBo** [comment]
Also getting this with 7.17.2 and Unity 2018.2.12f1 while running on a Android device.

**Comment by huran438** [comment]
Have same issue: #308

**Comment by huran438** [comment]
Facebook has tons of specialists and cant resolve this annoying issue. SDK is not updating for 2-nd month now. It's normal?

**Comment by KylinChang** [comment]
That's actually a debug log and we remove it in v7.18.0. Close the issue.
