### ISSUE TITLE
v7.17.2-iOS : can not login on iOS 13

### ISSUE THREAD

**Issue by dqh147258** [facebook/facebook-sdk-for-unity#333]
It works well on iOS 12 , but when I run my app on iOS 13 , it can not login . 

On iOS 13 , if I have install the facebook app already , the operation system would show a dialog for opening facebook , but click either "ok" button or "cancel" button has no response ; If I have not install the facebook app , I can not wake the ime up while I want to input the facebook account and passward .  

There are some similar issues on other facebook sdk for other languages or tools.

https://github.com/facebook/facebook-swift-sdk/issues/482

https://github.com/facebook/facebook-swift-sdk/issues/495

https://github.com/facebook/facebook-objc-sdk/issues/1013

**Comment by KylinChang** [comment]
Hey @dqh147258 , what's the FBiOSSDK version you are using? The issue should be fixed in the latest SDK.

**Comment by dqh147258** [comment]
Hi @KylinChang , My Unity SDK version is 7.17.2 , I have tried to change the iOS sdk version from 5.3.0 to 5.2.2 , 5.4.1 and 5.5.0 . Among them , versions 5.2.2 and 5.3.0 have no effect , version 5.4.1 and 5.5.0 can wake ime up if facebook has not been installed , but can not get response when I click the "cancel" or "ok" button if facebook has been installed.

**Comment by dqh147258** [comment]
@KylinChang By the way , my test devices is iPhone6s(ML7E2CH/A) , system version is 13.0(17A5547d).

My develop environment : 

Xcode Version : 10.1(10B61)
Unity Version :   2017.4.27f

**Comment by Meilu** [comment]
We are having the same issue, both on simulator and on a device. After clicking on the continue button no browser will open after calling `LoginManager().logIn`

**Comment by charles-yeh** [comment]
My situation is loginWithReadPermission's callback never returns on iOS 13. 
Unity 2019.1.14f1, Facebook SDK 7.17.2, FB iOS SDK showed 5.6.0.

**Comment by charles-yeh** [comment]
Okay... the way I fix that is before call LoginWithReadPermission(), I will check FB.isLoggedIn. If FB is still in a valid logged-in status, do not call that LoginWithReadPermission() to get stuck without callback, instead just skip it (you can retrieve still valid access token from AccessToken.currentAccessToken ...). Get that work on both iOS 12/13.  Hopefully this work around helps...

**Comment by dqh147258** [comment]
When I update my device system from a beta version of iOS 13 to a release version the problem disappeared.
So it is a bug of iOS 13 and it has been fixed in newest release version.

**Comment by PeanutPro** [comment]
This is still hapenning on Unity sdk version 7.18.0 with ios 13.1

**Comment by pixiongames** [comment]
> This is still hapenning on Unity sdk version 7.18.0 with ios 13.3.
> 
> Basically the native ui that appears is bugged, I can not click cancel or open in the middle. It is possible to click the cancel in the top left tho.

I quote PeanutPro.
We are experiencing the same issue with the latest Facebook Unity SDK (7.18) and iOS 13.3.1

Is there any news on this?

**Comment by rossojr92** [comment]
Hi @pixiongames,

I'm using

Unity: 2017.4.36f1
Facebook SDK: 7.18.1
iOS: 13.3.1

and having a similar issue. When I call LogInWithReadPermissions, it opens Safari and it asks me if i wish open the facebook App. If I click on Cancel, it just remains there. If I click on Open, it brings me to the facebook app where I can do the login. After the login process, it returns on the safari page and stay there.

I can't find any reasonable solution for this. Did you have find something on this?
Thanks for your help!

Best regards,
Andrea

**Comment by rossojr92** [comment]
A small update:

I've achieved Facebook Login with Unity 2017.4.36, Facebook SDK 7.18.1 and iOS 13.3.1.
I've done this steps (no code required):

- Launch the login flow normally.
- The browser is opened. When it asks to open facebook app I click cancel (you can also click open, but in this case you will be redirected to an app page where you will click "Consent" and it will returns you to the browser page)
- On Browser I navigate to the facebook login page. Log In here.
- Close the app, relaunch and restart the flow.
- From the browser page there is now a "Confirm" button that triggers the correct login callback to the app.

This does not fix the problem that the login flow doesn't work with the Facebook App. Is there a way to force Unity to launch the Facebook App instead of browser?

**Comment by crocoking** [comment]
你们解决了吗？我也碰到同样的问题。

**Comment by h3902340** [comment]
> 你们解决了吗？我也碰到同样的问题。

我後來解決了。我把專案資料夾的根目錄的所有能刪除的資料夾都刪除，然後重啟專案，讓Unity重建這些資料夾，就解決了。這是從Unity 2018升級至Unity 2019 所產生的問題。
我之前開了一個Unity 2019的空白專案，發現是能夠成功在iOS登入，因此確認是升級Unity所造成的問題。
英文回覆我懶得打了。。

**Comment by gpiffaretti** [comment]
how is this thread closed? I'm experiencing this issue as well. Unity 2019.3.2, Facebook SDK 7.19.2, XCode 11.4.1 and iOS 13.4.1.
Tried importing different Facebook SDKs, tried changing versions in the Podfile. Changing the login flow to avoid calling LogInWithReadPermissions if user is logged in. Don't know what else to do and waiting for Facebook to fix this doesn't look like a good idea.
I'm really mad at this bug, we're not being able to ship because of this :(

**Comment by jasons-codes** [comment]
We have the same problem.
The problem occurs in the following order.
1. Enter the Facebook login screen
2. Click the 'Log in with the Facebook app' button.
3. Appear system dialog for this message = Open in "Facebook"?
4. Clicking the 'Cancel' and 'Open' buttons in the dialog does not respond
5. And after a while, the app crashes.

How can we solve this?

**Comment by jasons-codes** [comment]
Device: iPhone 11 Pro
iOS Version: iOS 13.4.1
Xcode Version: 11.4.1
Unity Version: 2019.3.2f1
FB SDK for Unity Version: 7.19.2

We have the same problem.
The problem occurs in the following order.

1. Enter the Facebook login screen
2. Click the 'Log in with the Facebook app' button.
3. Appear system dialog for this message => Open in "Facebook"?
4. Clicking the 'Cancel' and 'Open' buttons in the dialog does not respond.
5. And after a while, the app crashes.

How can we solve this?

**Comment by chrisspaceape** [comment]
Device: iPhone X
iOS: 13.4.1
Xcode: 11.2.1
Unity: 2018.4.22f1
FB SDK for Unity: 7.18.1

We had something slightly different but may still be worth trying the fix we did.
We were having issues with safari appearing and then disappearing when clicking 'Continue'.

There's an option in Project Settings -> Player -> iOS -> Render Extra Frame on Pause.
Worth a try to turn that option 'off' and then try again. It fixed it in our situation.

<img width="304" alt="RenderExtraFrame" src="https://user-images.githubusercontent.com/17405401/84247537-2a860f80-ab00-11ea-9a17-9114ac615abf.png">

**Comment by edun81** [comment]
@chrisspaceape  Thanks !! You saved me.

**Comment by flypart** [comment]
> Device: iPhone X
> iOS: 13.4.1
> Xcode: 11.2.1
> Unity: 2018.4.22f1
> FB SDK for Unity: 7.18.1
> 
> We had something slightly different but may still be worth trying the fix we did.
> We were having issues with safari appearing and then disappearing when clicking 'Continue'.
> 
> There's an option in Project Settings -> Player -> iOS -> Render Extra Frame on Pause.
> Worth a try to turn that option 'off' and then try again. It fixed it in our situation.
> 
> <img alt="RenderExtraFrame" width="304" src="https://user-images.githubusercontent.com/17405401/84247537-2a860f80-ab00-11ea-9a17-9114ac615abf.png">

Thanks, You really saved my life

**Comment by jasil1981** [comment]
Any update on this I am facing a similar issue after version upgrade of 9.0.

iOS: most of OS version
Xcode: 12.4
Unity: 2019.4.23
FB SDK for Unity: 9.0.1 and 9.0
