### ISSUE TITLE
[!] Error installing FBAudienceNetwork

### ISSUE THREAD

**Issue by Vah94** [facebook/facebook-sdk-for-unity#334]
Installing FBAudienceNetwork (5.5.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/qm/w9hxk8316t17zghj4zzmzy8r0000gn/T/d20190912-11515-h3tnhm/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.5.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7585k    0 7585k    0     0   134k      0 --:--:--  0:00:56 --:--:-- 70403
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

[Podfile.txt](https://github.com/facebook/facebook-sdk-for-unity/files/3605713/Podfile.txt)

**Comment by KylinChang** [comment]
Hi @Vah94 , do you have trouble downloading FBAudienceNetwork or you cannot integrate with FBAudienceNetwork?

**Comment by KylinChang** [comment]
Close the issue for no active response
