### ISSUE TITLE
iOS empty project with Facebook SDK integrated build error

### ISSUE THREAD

**Issue by NudeNULL** [facebook/facebook-sdk-for-unity#337]
Hello
For the last half of the year I wasn't able to use any of the newer versions of Facebook SDK after 7.15.1.

Soon Apple will reject any builds that contain some deprecated functionality from Facebook SDK  7.15.1, so I have to move to the latest version, which doesn't work for me, here are the steps required to reproduce the error on my side, even if these are the same steps that are in the Getting Started section:

1. Create an empty test project (from Windows machine)
2. Import latest Facebook SDK
3. Unity complains that Facebook SDK uses obsolete API
4. Add to build settings examples scenes in correct order (Main Menu first)
5. Create an App in Facebook Developer page
6. Set in Facebook settings in Unity the Facebook App Name and Facebook App ID
7. Save all that stuff and exit Unity
8. Sync all changes via Github
9. Open project in Unity (from Mac OS machine)
10. Build the game into Destop folder (exported project was named as in tutorial - unity_ios)
11. Open xcodeproj file
12. Run on any device
13. When building get this error:
	Lexical or Preprocessor Issue Group
		/Users/USER_NAME/Desktop/unity_ios/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityUtility.h:19:9: 'FBSDKShareKit/FBSDKShareKit.h' file not found
			/Users/USER_NAME/Desktop/unity_ios/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityUtility.mm:19:9:
			In file included from /Users/USER_NAME/Desktop/unity_ios/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityUtility.mm:19:

I hope you can help me.

Best Regards
Gleb

**Comment by NudeNULL** [comment]
I found that after xcode project export from Unity it misses the Framework folder

**Comment by iManchaDev** [comment]
@NudeNULL  Same issue here, any solutions to date?

I see the same error here: [](https://github.com/facebook/facebook-sdk-for-unity/issues/259)
@KylinChang
Issue was fixed, not sure why it is occurring again?

**Comment by NudeNULL** [comment]
> @NudeNULL Same issue here, any solutions to date?
> 
> I see a similar issue reported here: #259
> @KylinChang
> Issue was fixed, not sure why it is occurring again?

In my case I have made a lot of changes to fix it, and I am not sure which one worked:
1. In Unity set the stripping level to low, also you can try to disable engine code stripping, not sure if it was the reason.
2. Install or update cocoapods to the latest version, make sure you don't get any errors in terminal, and the most important restart you machine, in my case it started to work only after restart
3. Use a faster Mac OS machine, it can be that our iMac 2013 with HDD and 60 minutes+ per build, maybe was freezing so hard while building so that these libraries were not completely downloaded due to some connection issues, maybe connection time out, not sure on that because we didn't get any errors, but also it was working not every time, some times I had to build again and again until the libraries are added succesfully into xcode project

So in order to be sure that everything works fine you have to find out that the xcode project folder contains the .xcworkspace file, open only this file in order to load all needed libraries and build without errors.

After a couple of weeks we bought a brand new Mac Mini 2018 i5 and it runs super fast, so no more freezes also, and every build now have the .xcworkspace in it.

Hope it helps ;)

**Comment by iManchaDev** [comment]
@NudeNULL 

Finally got it working, it was actually quite simple after reading the change logs for :
v7.17.0 Facebook SDK
Modified:
Switch to use cocoapods and maven to pull Facebook iOS/Android SDK..

All I did was navigate via terminal to the directory of the project, type 'pod install' and it will pull and install the necessary pod files in the pods folder, and generate a new xworkspace project file, then in xcode open the project using the xworkspace instead of xcodeproj.

Clean build folder under 'product' menu just in case, then run a new build and all good to go.

**Comment by KylinChang** [comment]
Hi @NudeNULL , @iManchaDev , sorry for late response. UnitySDK is now using cocoapods and maven to pull Facebook iOS/Android SDK instead of bundling them together with the SDK. Usually Unity should run the pod install for exported iOS project, if not, you should run `pod install`.
