### ISSUE TITLE
UIWebview Deprecated warning from Apple

### ISSUE THREAD

**Issue by ryusora** [facebook/facebook-sdk-for-unity#338]
Hi guys, 
Currently we got a warning from apple about the UIWebview was deprecated. I know that facebook sdk iOS was fixed that warning on version 5.5.0, but thing is Facebook SDK for Unity is using Bolt framework which still contains the UIWebview. Do you have any plan on removing Bolt framework same as facebook sdk iOS?

Thanks

**Comment by KylinChang** [comment]
Hi @ryusora , the latest Unity SDK already removed Bolts framework.

**Comment by yagodar** [comment]
@KylinChang Indeed, Bolts still required FBUnityUtility.mm. And Bolts steel in the Dependencies.xml. I'm using Unity SDK 7.17.2

**Comment by yagodar** [comment]
@KylinChang I see that commit, removing Bolts:
https://github.com/facebook/facebook-sdk-for-unity/commit/185ba0420107f4f08a5898b17f7505fe47fa3fb4

In github repo yes - removed. BUT in downloadable SDK unitypackage it still exists - from https://developers.facebook.com/docs/unity/

**Comment by yagodar** [comment]
@KylinChang looks like I found why.
Release of Unity SDK 7.17.2 -  Jul 18
https://github.com/facebook/facebook-sdk-for-unity/commit/f76fd1cec1f08a36d90b21c8ab74cba1168f0d84

Removing Bolts -  Jul 23.

Temp solution, who stuck on this too - download version of SDK from github.

**Comment by happypepper** [comment]
@KylinChang can you please bump the version? the latest downloadable sdk version from the official site still has this problem

**Comment by KylinChang** [comment]
Hi @happypepper @yagodar , we will release next week.
