### ISSUE TITLE
Issue on iOS caused by IOSInit

### ISSUE THREAD

**Issue by fmor-zz** [facebook/facebook-sdk-for-unity#34]
The current version of Facebook SDK for Unity (7.8.0) doesn't build the project with the **Configuration->Script Backend : Mono2x**, only works with **IL2CPP**.

Error message:
`SystemException: Duplicate native method found : IOSInit. Please check your source carefully.`

**Comment by bblpny** [comment]
Hello fmor-zz, I'm not from Facebook but I am guessing that you have some .cs or .mm files left over from before facebook updated to dlls. I suggest that you first make a backup of your project, then delete the entire FacebookSDK folder, any leftovers that facebook installed to the plugins directory (Basically, anything that you suspect came with facebook sdk then finally reimport the unitypackage. 

If this is a fresh install of the sdk ( as in, you did not have a earlier version installed ) please completely ignore my statement above.

**Comment by ehudros** [comment]
Happens to me as well. Any idea how to work around it?

**Comment by swiese** [comment]
Report bugs to https://developers.facebook.com/bugs

**Comment by JoRouss** [comment]
Hey, I've read that reverting to 7.7.0 fixes the issue.
http://answers.unity3d.com/questions/1230041/duplicate-native-method-iosinit.html

I wanted to know if upgrading from 7.8.0 to 7.9.0 fixes it?

**Comment by JoRouss** [comment]
Upgraded to 7.9.4. It fixed it.

**Comment by Vixxd** [comment]
I too was using Facebook SDK 7.8.0 and upgrading to 7.9.4 fixed this, on Unity 5.5.3p3. I am now able to debug on an iOS device using MonoDevelop and building with Mono2x selected in the player settings
