### ISSUE TITLE
We urge you to fix #278 ASAP

### ISSUE THREAD

**Issue by armnotstrong** [facebook/facebook-sdk-for-unity#348]
Issue #278 has been reported in July, and now it's November,  it has been 4 months, but still, it's not fixed, Your business guys kept pushing us to upgrade the SDK version, meanwhile it can't be compiled, this is ridiculous, please fix that ASAP.

**Comment by KylinChang** [comment]
Hi @armnotstrong , FB AN SDK v5.6.0 is released and it's using Cocoapods/Maven to pull the latest SDK as FB Unity SDK, it should work now. I suggest reporting a bug in https://developers.facebook.com/bugs/ so that we can react more quickly.
