### ISSUE TITLE
7.18.0 - iOS - module 'FBSDKCoreKit' not found when using Unity Cloud Build

### ISSUE THREAD

**Issue by eladleb** [facebook/facebook-sdk-for-unity#350]
## Environment

- Unity Editor Version: `2019.2.11f1`
- Unity SDK Version: `7.18.0`
- Installation Platform & Version: `iOS ` XCode 10.2'

Starting a few days ago, we are seeing iOS builds on Unity Cloud Build failing with this error:

Compiling FBSDKGraphErrorRecoveryProcessor.m
/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:24:9: module 'FBSDKCoreKit' not found

Expected to build correctly as it did a week ago. We have not made any related changes to our code.
The builds now fail consistently with the same error.

**Comment by eladleb** [comment]
Looks like this happened because of a new Facebook SDK release.
The transition from FBSDKCoreKit (5.8.0) to FBSDKCoreKit (5.10.0) seems to be the culprit.

There is already an open issue on the iOS SDK so closing this one.
[(https://github.com/facebook/facebook-ios-sdk/issues/1105)]

**Comment by pistoleta** [comment]
This is not fixed on the Facebook Unity SDK 7.17-2.1 launched on February 3rd, although the change log says it's fixed :
https://developers.facebook.com/docs/unity/change-log#v7_18_1. 
We still have to modify the dependency files manually.
