### ISSUE TITLE
Bolts didn't installed and can't find in pods file

### ISSUE THREAD

**Issue by wheatleyscience** [facebook/facebook-sdk-for-unity#356]
Hi,

I removed all of my plugins and reinstall everything recently. But i recognized that, there isn't bolts pod in my ios build. Is it normal? Is there any change about bolts? Or did i missed some steps? Can you inform me about that issue. Thank you for your help.

Ps: i can succesfully get build from xcode and my game is working but there is too much performance problem when device have an internet connection, which is new thing for my game, i am suspecting about this issue.

**Comment by KylinChang** [comment]
Hi @wheatleyscience , the bolts framework is already removed because of deprecated UIWebView.  Have you found the reasons of your performance issue?
