### ISSUE TITLE
OpenSSL not found when using Unity Hub

### ISSUE THREAD

**Issue by Duke74** [facebook/facebook-sdk-for-unity#365]
## Issue description
When Unity is launched using the Unity Hub, we can see the error : `OpenSSL not found. Make sure that OpenSSL is installed, and that it is in your path.` even if openssl is installed correctly and added to the path variable.

Maybe a fix could be found for this ?

## Workaround
Launch Unity directly do not use Unity Hub

## Environment

- Unity Editor Version: `2018.3.9f1`
- Unity SDK Version: `7.18.0`

**Comment by ttermeer-reboundcg** [comment]
Same here on Unity 2018.4.14f1 after I updated Unity Hub to 2.2.1

**Comment by Shyrou** [comment]
Same here. I think the Unity version doesn't really matter. I have 2017.4.34

**Comment by ttermeer-reboundcg** [comment]
So this is a bug from Unity Hub that breaks environment variables
https://forum.unity.com/threads/unity-hub-2-2-1-broken-environmental-variables.788924/

Delete User level PATHEXT variable in Windows.

**Comment by Duke74** [comment]
Yes so I'll close the issue as it is a bug from Unity Hub, thanks @ttermeer-reboundcg for the solution !
