### ISSUE TITLE
Error on android after upgrade from FBSDK 7.11 to 7.18

### ISSUE THREAD

**Issue by kultie** [facebook/facebook-sdk-for-unity#367]
When app open on android android studio's logcat output this
```
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '[FB app id]' does not exist, cannot be loaded due to missing permissions, or does not support this operation.
```
And I cannot use the facebook login feature like it's use to be in 7.11
When ever i try to use facebook login the log cat out put this
```
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
```
I tried to use wrap try catch block for the operation and got this:
```
****FACEBOOK ERROR: Object reference not set to an instance of an object.
    <MergeFacebook>c__AnonStorey1:<>m__0(ILoginResult)
    Facebook.Unity.CallbackManager:TryCallCallback(Object, IResult)
    Facebook.Unity.CallbackManager:CallCallback(Object, IResult)
    Facebook.Unity.CallbackManager:OnFacebookResponse(IInternalResult)
```
Does this object of try catch same as object with id that didn't exist?

**Comment by KylinChang** [comment]
Hey @kultie , have you set FB App ID in setting? If so, can you send me your FB App ID?

**Comment by kultie** [comment]
@KylinChang 
Yeah the app id been missing all the time
I cannot believe that I didn't check about App ID since i'm using a utitlities to auto change the fb's app id setting to match my build. This hasn't been an issue before, but this time around it's keep getting reset to empty string. I have to manually set it
I need to check the utilities tool for the new fb sdk
