### ISSUE TITLE
UIWebView deprecated issue

### ISSUE THREAD

**Issue by 1901** [facebook/facebook-sdk-for-unity#368]
Hi, I used the latest Unity SDK (`facebook-unity-sdk-7.18.0`). When I submitted the App to App Store got UIWebView deprecated warning. 
`
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
`

https://github.com/facebook/facebook-ios-sdk/issues/1035
There mentioned the problem was fixed on facebook-ios-sdk v5.5.0, but `Dependencies.xml` still required 5.2. Please upgrade the dependencies, thanks.

```
    <iosPods>
        <iosPod name="FBSDKCoreKit" version="~> 5.2" />
        <iosPod name="FBSDKLoginKit" version="~> 5.2" />
        <iosPod name="FBSDKShareKit" version="~> 5.2" />
    </iosPods>
```

**Comment by tiffanym19** [comment]
encountering this issue? whats the solution for this?

**Comment by Tostifrosti** [comment]
+1

**Comment by 1901** [comment]
Just replace the version with `5.5`
```
<iosPods>
    <iosPod name="FBSDKCoreKit" version="~> 5.5" />
    <iosPod name="FBSDKLoginKit" version="~> 5.5" />
    <iosPod name="FBSDKShareKit" version="~> 5.5" />
</iosPods>
```

**Comment by tiffanym19** [comment]
Thank you it works :)

**Comment by KylinChang** [comment]
You can change the version in Podfile, or run `pod install --repo-update`

**Comment by bachirelkhoury** [comment]
This is still happening and we're on version 7.1.1

```
<iosPods>
    <iosPod name="FBSDKCoreKit" version="~> 7.1.1" />
    <iosPod name="FBSDKLoginKit" version="~> 7.1.1" />
    <iosPod name="FBSDKShareKit" version="~> 7.1.1" />
    <iosPod name="FBSDKGamingServicesKit" version="~> 7.1.1" />
</iosPods>
```
