### ISSUE TITLE
Is it possible to know if Facebook is installed?

### ISSUE THREAD

**Issue by alamboley** [facebook/facebook-sdk-for-unity#37]
Hey, using `ShareDialogMode.NATIVE` crashes if the user doesn't have Facebook app installed (on iOS). Is there a method to know if Facebook is installed or not and so moving to web?

`ShareDialogMode.AUTOMATIC` by default sends directly on Web.

**Comment by mingflifb** [comment]
What are you trying to share? The automatic mode tries to find the best option depending on what's being shared, so somethings might go to the SafariVC whereas others will go native if the app is available.

**Comment by alamboley** [comment]
Thanks for the answer. It is a `FB.ShareLink`. On iOS the automatic mode opens a Webview even if the app is installed so that's an issue for my client.

**Comment by swiese** [comment]
This sounds like a bug. Please report it to https://developers.facebook.com/bugs
