### ISSUE TITLE
Platform dependent bindings.

### ISSUE THREAD

**Issue by glock45** [facebook/facebook-sdk-for-unity#4]
hi @swiese --

I am curious why the SDK uses bindings to iOS & Android SDKs. Why it's not a C# monster ( with some parts from Windows Phone SDK )? Is it about using a stable codebases or something else ? 

best,
dk

**Comment by swiese** [comment]
There several reasons but the two main reasons are.
1. Unity doesn't have support for a webview controller. This means that we can't easily have a cross platform way of showing our dialogs unless we wanted to bring in a lot of code to render our dialogs.
2. The FacebookSDK interacts directly with the native apps for showing some dialogs and can even do convenient things like log you in without opening a dialog on Android. To do this kind of integration we have to write platform specific code. 

Conveniently both of these problems are solved if we just call directly into the facebook sdk for ios, android, and js.
