### ISSUE TITLE
Issue: Viewability validation failed for Native Ads

### ISSUE THREAD

**Issue by lukeWW** [facebook/facebook-sdk-for-unity#44]
I'm using the version 7.9.0

The Ad GameObject that is centered on the screen, is wrongly detected as not visible. The log says:
`Viewability validation failed: GameObject is not on screen. (x axis)`
`Native ad viewability check for unique id 0 returned success? False`

I've inserted a log in the **checkGameObjectViewability** method of **AdHandler** and I noticed that the position calculated is wrong: 
`positionOnScreen.x: -214.9999 >  screenSize.width:1080 - width:430`

In my Unity project (2D) I've a Canvas with a Canvas Scaler with the MainCamera positioned at the origin.

Maybe something wrong in the **calculateWorldPosition** method?

**Comment by swiese** [comment]
This is not the repo for the audience network sdk. Please report bugs for audience network at https://developers.facebook.com/bugs
