### ISSUE TITLE
Suddenly App Crashs because of FBSDKEventDeactivationManager.m line 64

### ISSUE THREAD

**Issue by Khaled-Wolf** [facebook/facebook-sdk-for-unity#453]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2017.4.40`
- Unity SDK Version: `7.19.2`
- Installation Platform & Verison: `[iOS]` version `13` (82%) iOS 12.x.x (15%)

## Goals

Players launch the game and be able to login to FB normally

## Expected Results

players be able to launch the game without crash

## Actual Results

the game is suddenly crashing at the launch, suddenly I'm getting a spike of crashes with velocity crash alert from Crashlytics

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1ac8eaa48 __exceptionPreprocess
1  libobjc.A.dylib                0x1ac611fa4 objc_exception_throw
2  CoreFoundation                 0x1ac7ee5a8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1ac8eeaf4 ___forwarding___
4  CoreFoundation                 0x1ac8f0a7c _CF_forwarding_prep_0
5  mygame                    0x104ba8904 +[FBSDKEventDeactivationManager updateDeactivatedEvents:] + 64 FBSDKEventDeactivationManager.m:64)
6  mygame                    0x104bd2748 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 259 (FBSDKServerConfigurationManager.m:259)
7  mygame                    0x104bb65ec __69+[FBSDKGraphRequestPiggybackManager addServerConfigurationPiggyback:]_block_invoke + 155 (FBSDKGraphRequestPiggybackManager.m:155)
8  mygame                    0x104bb4e70 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 41 (FBSDKGraphRequestMetadata.m:41)
9  mygame                    0x104bb2738 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 806 (FBSDKGraphRequestConnection.m:806)
10 mygame                    0x104bb262c -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 839 (FBSDKGraphRequestConnection.m:839)
11 mygame                    0x104bb223c __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 788 (FBSDKGraphRequestConnection.m:788)
12 CoreFoundation                 0x1ac8bd95c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation                 0x1ac7c0ed0 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:]
14 mygame                    0x104bb2000 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 767 (FBSDKGraphRequestConnection.m:767)
15 mygame                    0x104bb14b4 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 634 (FBSDKGraphRequestConnection.m:634)
16 mygame                    0x104baf60c __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 242 (FBSDKGraphRequestConnection.m:242)
17 libdispatch.dylib              0x1ac5b6610 _dispatch_call_block_and_release
18 libdispatch.dylib              0x1ac5b7184 _dispatch_client_callout
19 libdispatch.dylib              0x1ac569190 _dispatch_main_queue_callback_4CF$VARIANT$mp
20 CoreFoundation                 0x1ac8685e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
21 CoreFoundation                 0x1ac8635d8 __CFRunLoopRun
22 CoreFoundation                 0x1ac862adc CFRunLoopRunSpecific
23 GraphicsServices               0x1b6803328 GSEventRunModal
24 UIKitCore                      0x1b097063c UIApplicationMain
25 mygame                    0x1049e5a20 main + 33 (main.mm:33)
26 libdyld.dylib                  0x1ac6ec360 start
![image](https://user-images.githubusercontent.com/65023622/87153943-f8afc680-c2c0-11ea-87fa-84eed3f636b9.png)

## Steps to Reproduce

What are the steps necessary to reproduce this issue?
I have no idea how to reproduce, the game is published one week ago without this crash and it suddenly spiked during last hour (250 crash per one hour!)

**Comment by MagicMiikka** [comment]
https://developers.facebook.com/status/issues/1739188102911114/

**Comment by Oliverccccct** [comment]
The issue should be fixed now.
