### ISSUE TITLE
bolts-android-1.4.0.jar causes Unity 5.5 gradle build to fail

### ISSUE THREAD

**Issue by tallior** [facebook/facebook-sdk-for-unity#46]
The included bolts android library contains an AndroidManifest.xml as well as no code inside (not sure this is what its meant to include):
![image](https://cloud.githubusercontent.com/assets/7803582/20640751/36a7a7ca-b3f0-11e6-8ad9-08d7dd756b1b.png)

When trying to build a game that includes the FB SDK with Unity 5.5f1 (using gradle), the build fails due to an error (AndroidManifest.xml already exists).

Looking at the Bolts repository, i see they have 2 artifacts (tasks and applinks). I am not even sure this .jar is needed at all.

**Comment by PimDeWitte** [comment]
+1

**Comment by tallior** [comment]
any updates?

**Comment by tallior** [comment]
Also reported as a Facebook bug: https://developers.facebook.com/bugs/1354325697931975/

**Comment by tallior** [comment]
Sorry, the issue is that AndroidManifest.xml is contained twice in the .jar:

No, AndroidManifest.xml is included _twice_ inside the JAR in the repro project attached to this issue (GradleJAR.zip)

# unzip -l bolts-android-1.4.0.jar

Archive:  bolts-android-1.4.0.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
      334  01-15-16 15:37   AndroidManifest.xml
      836  01-15-16 15:37   classes.jar
        0  01-15-16 15:37   aapt/
      334  01-15-16 15:37   aapt/AndroidManifest.xml
        0  01-15-16 15:37   assets/
        0  01-15-16 15:37   aidl/
        0  01-15-16 15:37   res/
 --------                   -------

**Comment by swiese** [comment]
Issue tracked at https://developers.facebook.com/bugs/1354325697931975/
