### ISSUE TITLE
Feature Request: not use about libSwift*.dylib

### ISSUE THREAD

**Issue by zelinDavid** [facebook/facebook-sdk-for-unity#469]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals
  use fb-sdk-for-unity but not including those libSwift*.dylib in my app. for it increased my app size. 

so i wonder know is it supported in the latest version of sdk? I dont find a way to make it out.

**Comment by KylinChang** [comment]
The FB iOS SDK is using swift so we need to have swift dylib and you can strip swift symbol to reduce app size while uploading your app
