### ISSUE TITLE
AppCompat library increases dex count significantly

### ISSUE THREAD

**Issue by PimDeWitte** [facebook/facebook-sdk-for-unity#47]
From my last calculations it increases it by about 12k, which is pretty bad. Is there a way to only ship this with the required styles. These are the required styles:
```
 <style name="com_facebook_activity_theme" parent="@style/Theme.AppCompat.NoActionBar">
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowNoTitle">true</item>
    </style>
    <style name="com_facebook_auth_dialog" parent="@style/Theme.AppCompat.Dialog">
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowIsFloating">true</item>
    </style>
```

**Comment by PimDeWitte** [comment]
AppCompat V7	appcompat-v7:21.0.0	12,324

https://www.contentful.com/blog/2014/10/30/android-and-the-dex-64k-methods-limit/

**Comment by khld85** [comment]
I am having the same issue, I downgrade to 7.8 until I find a solution for this issue

Multi-Dex is not a good option according to Unity Official
https://forum.unity3d.com/threads/multidex-support-on-android.325429/#post-2110624

**Comment by liortal53** [comment]
From what i've seen, it's the Android support library that adds a lot to the method count.
Is there any option to analyze the APIs that are needed by the FB SDK and create a process that will generate a "stripped down" version of those libraries ?

**Comment by wang-yichun** [comment]
same question..
waiting at 7.8

**Comment by swiese** [comment]
The core FB android SDK requires these libraries. On normal Android Apps this is not an issue due to the support for multi dex and proguard.

**Comment by avrahamy** [comment]
Well, there is a huge amount of Unity games using the Facebook SDK, and Unity is not a "normal Android App".
Please fix this issue!

**Comment by icyh4mmer** [comment]
I also had a problem with 7.9.4, in my case it increased ref count from 46k to 86k, which is really strange, then I tried 7.8.0, and ref count only increased from 46k to 52k.

**Comment by ocracy** [comment]
Change @style/Theme.AppCompat.NoActionBar into @style/Theme.Light.ActionBar
and @style/Theme. AppCompat.Dialog into @style/Theme.Dialog

**Comment by Leandros** [comment]
Why was this closed? It's still an issue.

**Comment by 2rusbekov** [comment]
Yes, why this is closed? It's big issue

**Comment by Whyser** [comment]
Still an issue. I'm trying desperately to minimize the ref count, but this library is simply too big...

**Comment by LoungeKatt** [comment]
@swiese Unity does **not** support multidex (without some rather extravagant workarounds). I may be mistaken, but isn't the entire purpose of a dedicated Unity SDK because it is different?

For anyone else that stumbles across this issue and needs a solution:
https://forum.unity.com/threads/multidex-support-on-android.325429/
https://medium.com/@abhpatidar/solving-unity-dex-issue-538e134c8809

It's unfortunate that we are trapped between two dev teams that are both unwilling to help users.
