### ISSUE TITLE
Facebook Deep Link in Unity3D equal to null

### ISSUE THREAD

**Issue by Artuom193** [facebook/facebook-sdk-for-unity#474]
Question - why is Facebook Deep Link in Unity3D always null? My colleagues who work in Android Studio have never faced such problems. I think it's just that the Facebook SDK for Unity is made of sticks and crutches, because I haven't been able to achieve absolutely anything with it for two weeks now. This is a complete failure.

- Unity Editor Version: `2019.3.0f5`
- Unity Facebook SDK Version: `7.21.2`

## 5. My code:

```C#
void Awake()
{
if (FB.IsInitialized)
        FB.ActivateApp();
    else
    {
        FB.Init(() => {
            FB.ActivateApp();
        });
    }
}

public void Click()
{
    FB.Mobile.FetchDeferredAppLinkData(DeepLinkCallback);
}

void DeepLinkCallback(IAppLinkResult result)
{
    if (!string.IsNullOrEmpty(result.Url))
    {
        _floats.DeepLink = result.Url; // Deep Link = null (????????????)
        Debug.Log("Deep Link: " + _floats.DeepLink);
    }
    SceneManager.LoadScene(2);
}

void Update()
{
    DontDestroyOnLoad(this);
}
```
## 6. I tested Deep Link with Facebook Deep Link Tester. Deep Link looked something like this:
```
SS://testDeep
```

## 9. Removing scheme from AndroidManifest and Facebook settings didn't help me either. Also, I tried enabling "Native or desktop app?" in the Facebook app settings, but it was also useless

**Comment by Artuom193** [comment]
The problem has been resolved.

**Comment by wesclarkemag** [comment]
@Artuom193 can I ask how you managed to solve your problem?

**Comment by xansrnitu** [comment]
@Artuom193 can you please tell how you have solved the issue? Thanks.
