### ISSUE TITLE
Windows Phone Support

### ISSUE THREAD

**Issue by hassanselim0** [facebook/facebook-sdk-for-unity#5]
It would be great if you can add support for Windows Phone and Windows Store (Unity's Universal 8.1 build target).
There is already a version of Facebook SDK for normal Windows Phone apps, so I don't see why it would be hard to integrate it into this Unity SDK. (if there is something I'm missing, please inform me)

I might attempt doing that by creating WP implementations for the abstract classes, but I'm still not familiar with how your code is laid out so it would take a lot of effort from me.

**Comment by swiese** [comment]
We haven't had time to get to feature but someone is possibly looking at adding this functionality 
https://github.com/facebook/facebook-sdk-for-unity/issues/9
