### ISSUE TITLE
The download server is down for the Unity SDK

### ISSUE THREAD

**Issue by Mattias-TB** [facebook/facebook-sdk-for-unity#502]
I have not received any reply on Twitter or the official help request via Facebook.

Trying to download the SDK from this page: https://developers.facebook.com/docs/unity/downloads using the top release ([8.1.1](https://origincache.facebook.com/developers/resources/?id=facebook-unity-sdk-8.1.1.zip)) only shows that the server is unreachable.

It does not seem to be my connection since the downdetector says the same: https://downforeveryoneorjustme.com/origincache.facebook.com?proto=https

**Comment by AndrewSpalato-FGMNT** [comment]
Same here, any updates or workarounds on this?

**Comment by adiohaion** [comment]
same here.

**Comment by adrianyip1222-unity** [comment]
Same here, it's been two days

**Comment by AlexZonov** [comment]
Same here!

**Comment by vizielod** [comment]
Could anybody from the Facebook SDK developer team inform us about the expected date of fixing this issue? I cannot proceed with my project because I should do the Facebook integration part.

**Comment by DiegoWojak** [comment]
Hi guys, today i tried download and it works for this link https://developers.facebook.com/docs/unity/change-log#v8_1_1, . Just click in Zip. I don't know why /downloads page.

Hope that help you out.

**Comment by vizielod** [comment]
@DiegoWojak nice, thank you. I was trying this as well on Wednesday, but it wasn't working that time.

**Comment by Mattias-TB** [comment]
The links are fixed.
