### ISSUE TITLE
Facebook Unity SDK XCode build error

### ISSUE THREAD

**Issue by YianChen75** [facebook/facebook-sdk-for-unity#508]
I updated the Facebook Unity SDK 8.1.0 to 9.0.0 and there was an error when building ios xcode

build error message

Undefined symbol: _OBJC_CLASS_$_ASPasswordCredential
Undefined symbol: _OBJC_CLASS_$_ASAuthorizationAppleIDCredential
Undefined symbol: _OBJC_CLASS_$_ASAuthorizationController
Undefined symbol: _OBJC_CLASS_$_ASAuthorizationPasswordProvider
Undefined symbol: _ASAuthorizationAppleIDProviderCredentialRevokedNotification
Undefined symbol: _ASAuthorizationScopeFullName
Undefined symbol: _OBJC_CLASS_$_ASAuthorizationAppleIDProvider
Undefined symbol: _ASAuthorizationScopeEmail

any suggestions ?

**Comment by YianChen75** [comment]
i add this code 


  const string GameKitFrameworkName = "GameKit.framework";
  const string AuthFramework = "AuthenticationServices.framework";
  [PostProcessBuild(101)]
  private static void PostProcessBuild_LinkGameKit(BuildTarget target, string buildPath)
  {
#if UNITY_EDITOR_OSX
      if (target == BuildTarget.iOS)
      {

          string projPath = PBXProject.GetPBXProjectPath(buildPath);
          PBXProject proj = new PBXProject();
          proj.ReadFromString(System.IO.File.ReadAllText(projPath));

          // embed gamekit into Unity framework target because its used in the facebooksdk
          Debug.Log("Embedding gamekit frameworks into UnityFramework target...");
          string targetGuid = proj.GetUnityFrameworkTargetGuid();

          proj.AddFrameworkToProject(targetGuid, GameKitFrameworkName, true);
          proj.AddFrameworkToProject(targetGuid, AuthFramework, true);
          proj.WriteToFile(projPath);
      }
#endif
  }

Solved the problem

**Comment by manpreet444** [comment]
I am facing same issue on building for ios, Where we need to add these lines of code
