### ISSUE TITLE
Android app crash on launch due to ClassNotFoundException for "com.facebook.FacebookContentProvider" 

### ISSUE THREAD

**Issue by juliodutra2003** [facebook/facebook-sdk-for-unity#509]
## Checklist
I[ve being on this for almost 2 days. Searched all the internet for an answer and the only reasonable answer i found it´s notr working.

I tried to insert this on my proguard-user.txt but it does any difference.
-keep public class com.facebook.* {*;}
-keep public class com.facebook.internal.* {*;}

## Environment

- Unity Editor Version: 2019.4.18
- Unity SDK Version: 9.0.0
- Installation Platform: Android

## Goals
I´m trying  to integrate Facebook SDK to my Android project.

## Expected Results

I expected to integrate the SDK and be able at least to build and run the project.

## Actual Results
 The project builds but the app crashes immediately with the error:
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime FATAL EXCEPTION: main
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime Process: com.inventplay.obsession, PID: 2281
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/lib/arm64, /data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.installProvider(ActivityThread.java:7073)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6613)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6508)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.access$1300(ActivityThread.java:220)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1865)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:107)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:235)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7441)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/lib/arm64, /data/app/com.inventplay.obsession-tNoDYlxly5uR0z8lLDo_MQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	at android.app.ActivityThread.installProvider(ActivityThread.java:7057)
2021/01/26 10:58:16.673 2281 2281 Error AndroidRuntime 	... 10 more

## Steps to Reproduce

Simply import the Facebook SDK 9.0.0 on any project and try to build for android.

## Code Samples & Details

I build from editor and run directly on my device. The app crashes immediately with the error above.

**Comment by juliodutra2003** [comment]
I´m using Googleplay services plugin and Googleplay resolver package which is a requirement for Googleplay services.

**Comment by juliodutra2003** [comment]
SOLVED!

*The problem was in the External Dependency Manager.*

External Dependency Manager does not do it´s job 100%. After installing the Facebook SDK the libraries was not incluided on Plugins/Android. After Run the "Resolve" function, a few libraries was found duplicated into different versions.

*Solution:*

After install the FACEBOOK SDK you need to re-run "Resolve" function of the External Dependency Manager as you can see in the image below:

![image](https://user-images.githubusercontent.com/21320383/106142761-a34de080-6150-11eb-998f-8eeedba0b066.png)

After that, go to the Plugins/Android folder and review all libraries. Try to identify if the facebook libraries are there and try to find any duplicate files (even on different versions).

![image](https://user-images.githubusercontent.com/21320383/106143306-5d454c80-6151-11eb-8a69-fb0626f55454.png)

**Comment by schabbs** [comment]
Did you have the Google Play Services Resolver package installed separately? If that's the case I think you should reopen this issue so the developers will know to update the dlls. To elaborate a bit more: the solution you suggested doesn't seem to fix it for me if I use the Play Services Resolver provided with the Facebook SDK but it will work if I download it separately from here https://github.com/googlesamples/unity-jar-resolver and add it in the project.

There's also another issue on this that's been open for ages but not resolved: https://github.com/facebook/facebook-sdk-for-unity/issues/393

**Comment by MarcoLavoro** [comment]
> Did you have the Google Play Services Resolver package installed separately? If that's the case I think you should reopen this issue so the developers will know to update the dlls. To elaborate a bit more: the solution you suggested doesn't seem to fix it for me if I use the Play Services Resolver provided with the Facebook SDK but it will work if I download it separately from here https://github.com/googlesamples/unity-jar-resolver and add it in the project.
> 
> There's also another issue on this that's been open for ages but not resolved: #393

do you use the version "external-dependency-manager-1.2.168"?

I hate facebook SO MUCH, they alway create some trouble in my projects...

**Comment by Atomiz2002** [comment]
2023 the issue still persists. I fail to understand what is so complicated about getting this to work and how could such simple issue persist for YEARS without a proper solution. The .ddls are nowhere to be found, not in Assets/Plugins/Android. There is some confusing gradle going on when clicking Display Libraries that contains some Facebook dependancies and still fails to run the game. This has been an issue ever since 7.x and now its on 16.x with the same issue not fixed for everyone. What are we supposed to do?
