### ISSUE TITLE
Login gets stuck in loop in 9.0.0 if Facebook app is installed

### ISSUE THREAD

**Issue by LongLostPenPal** [facebook/facebook-sdk-for-unity#519]
I had a similar issue, https://github.com/facebook/facebook-sdk-for-unity/issues/514
 but I'm not using AppsFlyer.
My situation :
Unity Editor Version: 2019.2.21f
Unity SDK Version: 9.0.0
when click FB login button in game , if user has login in WebView , it has a 'continue' button in WebView. Once the 'Continue' button is pressed user will jump back to game but FB.IsLoggedIn is false in FB login callback at this time。Login gets stuck in loop if user not login in WebView。
i use FB.LogInWithReadPermissions to login, not limit mode.
All works well for previous SDK versions ( 8.1.1) .
help please

**Comment by ppansy** [comment]
@LongLostPenPal Are you logging in using Facebook app or the in app WebView?
Providing repro steps and a sample project can help us debug this issue faster. Thanks!

**Comment by LongLostPenPal** [comment]
> @LongLostPenPal Are you logging in using Facebook app or the in app WebView?
> Providing repro steps and a sample project can help us debug this issue faster. Thanks!

I'm logging in using the in app WebView , and get error when lick "continue" button in WebView. 
Error Message:
`
LoginResult:
	Error: Invalid ID token from login response.
	RawResult: {"error":"Invalid ID token from login response.","callback_id":"3"}
	Cancelled: False
`

**Comment by ppansy** [comment]
This error can be caused by multiple reasons, please provide a sample project for us to debug further.
One possibility that has been brought up before is the system time can be changed manually in device settings, causing the AuthenticationToken to be considered expired.

**Comment by LongLostPenPal** [comment]
> This error can be caused by multiple reasons, please provide a sample project for us to debug further.
> One possibility that has been brought up before is the system time can be changed manually in device settings, causing the AuthenticationToken to be considered expired.

I changed a few test equipment and the problem did not reproduce. but it still gets stuck in loop if Facebook app is installed

**Comment by LongLostPenPal** [comment]
> > This error can be caused by multiple reasons, please provide a sample project for us to debug further.
> > One possibility that has been brought up before is the system time can be changed manually in device settings, causing the AuthenticationToken to be considered expired.
> 
> I changed a few test equipment and the problem did not reproduce. but it still gets stuck in loop if Facebook app is installed

I have solved this problem. Similar to this problem:
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md
, there are other similar SDKs in my project, thanks

**Comment by SebC99** [comment]
@LongLostPenPal we have the same error in our logs, without using AppsFlyer... would you mind sharing more details on the way you solved it?
Thanks!
