### ISSUE TITLE
Invalid Scope gaming_user_picture when using LoginWithTrackingPreference

### ISSUE THREAD

**Issue by MartinGonzalez** [facebook/facebook-sdk-for-unity#529]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2018.4.16`
- Unity SDK Version: `9.0.0`

## Goals

What do you want to achieve?
Use all available permissions when logging in documented in https://developers.facebook.com/docs/facebook-login/limited-login/ios

## Expected Results

What do you expect to happen?
Successful login with all data available

## Actual Results

What actually happened? Can you provide a stack trace?
Facebook message error:

```
Invalid Scopes: gaming_user_picture. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions
```

**Comment by ppansy** [comment]
`gaming_user_picture` is only available when you use [Facebook Login for gaming](https://developers.facebook.com/docs/games/gaming-services/login/). Sorry about the confusion, we will work on our documentation to avoid ambiguity like this
