### ISSUE TITLE
The imported type 'facebook.miniJSON.json' is defined multiple times

### ISSUE THREAD

**Issue by NCPLnaveen** [facebook/facebook-sdk-for-unity#53]
Hello everyone, 
                           I have project with is already integrated with Facebook or some other Facebook related SDK, after i build the project to iOS and Xcode was giving some errors related to 
Facebook framework. So what i did was i download the latest Facebook SDK and placed in unity, from then i'm getting this error  "The imported type 'facebook.miniJSON.json' is defined multiple times"  in Androidfacebook.cs file. I dont known how to resolve the issues. Please somebody suggest me what to do thank you.

**Comment by swiese** [comment]
You probably left some old files around after upgrading. Make sure you delete the FB plugin between upgrades.
