### ISSUE TITLE
First Name & Last Name null when using LoginWithTrackingPreference

### ISSUE THREAD

**Issue by MartinGonzalez** [facebook/facebook-sdk-for-unity#530]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2018.4.16`
- Unity SDK Version: `9.0.0`

## Goals

What do you want to achieve?
Get First & Last name just like LoginWithReadPermission does

## Actual Results

What actually happened? Can you provide a stack trace?
![image](https://user-images.githubusercontent.com/4130008/110375656-032d8600-8031-11eb-8a9e-7300f254b3d7.png)

Using LoginWithTrackingPreference with LoginTracking.ENABLED returns correctly first & last name but with LIMITED are null with `"email", "public_profile", "gaming_profile"` permissions

**Comment by ppansy** [comment]
Hi Martin, thanks for the feedback. FirstName & LastName are currently not supported by Limited Login. With that said, we are actively working Limited Login to include more functionality, this is something we will take into account.
