### ISSUE TITLE
Cant ShareLink twice

### ISSUE THREAD

**Issue by squigglyo** [facebook/facebook-sdk-for-unity#54]
Calling the shareLink function like this

Facebook.Unity.FB.ShareLink (new System.Uri ("https://developers.facebook.com/"),
			titleString",
			facebookMessage,
			new System.Uri (linkToImage),
			callback: null);

Works fine. But when I close Facebook and click the button again, nothing happens.

**Comment by swiese** [comment]
Please report bugs to https://developers.facebook.com/bugs
