### ISSUE TITLE
FB.Mobile.CurrentProfile().ImageURL is not valid image for some limited logins (FB SDK 9.0.0)

### ISSUE THREAD

**Issue by JuiseRovio** [facebook/facebook-sdk-for-unity#547]
- Unity Editor Version: `2019.4.18f1`
- Unity SDK Version: `9.0.0`
- Installation Platform & Verison: `[iOS]` version `14.x` (several versions)

## Goals

Use UnityWebRequest to display image from FB.Mobile.CurrentProfile().ImageURL when limited login is active

## Expected Results

Image is always shown when FB.Mobile.CurrentProfile().ImageURL is populated

## Actual Results

Some users imageURL:s don´t return image, eg. this one: https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=100003582183785&height=100&width=100&ext=1621771997&hash=AeSMHkK-EZluWa7hbvY 

That URL was populated for user https://www.facebook.com/jan.paszczak/ making a FB login with ATT declined.

## Steps to Reproduce

Make FB Login on certain device with certain user always reproes this.

## Code Samples & Details

here´s how limited login is done. The URL pasted above was logged from FB.Mobile.CurrentProfile().ImageURL

public static readonly string[] PermissionsToRequestLimitedLogin = new string[]{"public_profile"};
trackType = LoginTracking.LIMITED;
FB.Mobile.LoginWithTrackingPreference(trackType, permissionsToRequest, null, onLogin);

**Comment by ppansy** [comment]
Thanks for reporting! Our team has sent out a server side patch to fix this issue, expect it to be applied the next day or so, no actions needed from devs.
For context, this issue is specific for users that first logged in to the app before ~2014

**Comment by JuiseRovio** [comment]
Our QA confirmed it worked and old users was our case at least for several users. Thank you!
