### ISSUE TITLE
[iOS] can't log in anymore "-canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"" 

### ISSUE THREAD

**Issue by AVOlight** [facebook/facebook-sdk-for-unity#57]
Ok so this happened after adding Google Sign-In

adding this 
[super application:application
               openURL:url
     sourceApplication:sourceApplication
            annotation:annotation];

got my Facebook log in working again

**Comment by emannick** [comment]
Hi AVOlight i'm also facing the same problem in my unity3d project, where should i add above line.

**Comment by emannick** [comment]
Got it working, Thanks AVOlight

**Comment by enderGames** [comment]
I have the same error, where did @emannick put the said line?

**Comment by anshulkumar189** [comment]
I have also same error.

canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)

**Comment by dcarnelutti** [comment]
> Hi AVOlight i'm also facing the same problem in my unity3d project, where should i add above line.

Hi, how did you solve it? i can't figure it out. 

Thanks

**Comment by ChandniSharma** [comment]
I am also facing this error in sumulator and i don't have any ios device. how can I check FBlogin?
