### ISSUE TITLE
facebook login error on android

### ISSUE THREAD

**Issue by tamngonesv030** [facebook/facebook-sdk-for-unity#599]
![Screen Shot 2022-03-18 at 9 03 18 AM](https://user-images.githubusercontent.com/46778245/158923495-7081b72b-9ea3-4cb7-b411-db287d00bfb7.png)

I'm using Unity 2019.3.2 and Facebook sdk 11:

    List<string> perms = new List<string>() { "public_profile", "email"};
            FB.LogInWithReadPermissions(perms, AuthCallback);

 private void AuthCallback(ILoginResult result)
    {
        if (FB.IsLoggedIn)
        {
            FB.Mobile.SetAutoLogAppEventsEnabled(true);
            // AccessToken class will have session details
            var aToken = Facebook.Unity.AccessToken.CurrentAccessToken;
            // Print current access token's User ID
            Debug.Log(aToken.UserId + "  userTokenString " + aToken.TokenString);
            Debug.Log(aToken.UserId + "  ToJson " + aToken.ToJson());

        }
        else
        {
        }
    }

**Comment by owaisfb** [comment]
You should not be getting this error with the latest version (v12). Can you pull that and try again?
