### ISSUE TITLE
Android: ExceptionInInitializerError on Init

### ISSUE THREAD

**Issue by tayl0r** [facebook/facebook-sdk-for-unity#6]
About 5% of our DAU experiences this ExceptionInInitializerError every time on startup. Naturally, none of our devices get it.

We call FB.Init() fairly late in our app startup sequence, in this example our unity scripts begin doing stuff at 8 seconds into the game launch, and FB.Init() is called 14 seconds in, and then we get the exception about .5 seconds later (I can see our own code doing other stuff between FB.Init() and the exception).

```
> kyocera C5170
> OS: Android OS 4.0.4 / API-15 (IML77/release.20140730.032203)

Using Unity SDK v7.2.1 with FBAndroidSDK/4.7.0
AndroidJavaException: java.lang.ExceptionInInitializerError
Exception
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallStaticVoidMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.CallStatic (System.String methodName, System.Object[] args)
Facebook.Unity.Mobile.Android.FBJavaClass.CallStatic (System.String methodName, System.Object[] args)
Facebook.Unity.Mobile.Android.AndroidFacebook.CallFB (System.String method, System.String args)
Facebook.Unity.Mobile.Android.AndroidFacebook+JavaMethodCall`1[Facebook.Unity.IResult].Call (Facebook.Unity.MethodArguments args)
Facebook.Unity.Mobile.Android.AndroidFacebook.Init (System.String appId, Boolean cookie, Boolean logging, Boolean status, Boolean xfbml, System.String channelUrl, System.String authResponse, Boolean frictionlessRequests, Facebook.Unity.HideUnityDelegate hideUnityDelegate, Facebook.Unity.InitDelegate onInitComplete)
Facebook.Unity.FB.OnDllLoaded ()
Facebook.Unity.FB+CompiledFacebookLoader.Start ()
```

There is no matching java crash log in the Google Play console, the only error report is what you see here, from the built in Unity/C# error handling callback.

Any ideas?

**Comment by swiese** [comment]
I'm not sure clear why this would be happening and I haven't seen this before. 
It might be useful to see if there is any consistent devices or android versions where this error is happening.

For reporting bugs we would prefer if you report them to 
https://developers.facebook.com/bugs
They have better resources for triaging and reproducing issues.
