### ISSUE TITLE
Would you please fix the compile error!

### ISSUE THREAD

**Issue by CodeMasterYi** [facebook/facebook-sdk-for-unity#610]
We cannot find `FBSDKCreateContextDialog` & `FBSDKSwitchContextDialog` in the library.
We hear that you partially replace objective-c with swift! so they are in swift codes?
how to modify the Unity wrapper classes?

**Comment by CodeMasterYi** [comment]
waiting for you, v13.0.0.unitypackage!!!

**Comment by fahall** [comment]
bump

**Comment by fahall** [comment]
I posted this on their tech support forum awhile back. Maybe traffic there will push the dev team to get this SDK working again 🤷

https://developers.facebook.com/community/threads/5313337695388980/
