### ISSUE TITLE
Upgrade guide leads to 404

### ISSUE THREAD

**Issue by mastef** [facebook/facebook-sdk-for-unity#622]
https://developers.facebook.com/docs/unity

<img width="523" alt="image" src="https://user-images.githubusercontent.com/762297/173749415-718f434c-f56f-4135-a284-1c6996098271.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/762297/173749573-29897b0f-2a3a-455a-929e-91fdfad4d17d.png">
Upgrade guide leads to https://developers.facebook.com/docs/unity/upgrading-11.x which is a 404

I suppose it should link to [Upgrading to 13.2.0](https://developers.facebook.com/docs/unity/upgrading-7.x#1200to1320)

**Comment by Shivansh028** [comment]
can you explain this issue more briefly. 
i'm intrested in this.
and this is much similer to my experties,
so if you can so please 👍

**Comment by mastef** [comment]
Seems like the issue has been resolved in the meantime.
