### ISSUE TITLE
Undefined symbol errors when building for iOS in xcode with SDK v14.0.0

### ISSUE THREAD

**Issue by gamefish** [facebook/facebook-sdk-for-unity#626]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2021.3.5f1`
- Unity SDK Version: `14.0.0`
- Installation Platform & Verison: `[iOS]` version `any`

Linking error when building on iOS with 14.0.0 SDK
<img width="267" alt="Screen Shot 2022-07-09 at 01 12 20" src="https://user-images.githubusercontent.com/552806/178039517-15e68367-25d5-4224-8e31-37a7d2d3d04b.png">

## Steps to Reproduce

Upgrade to SDK 14.0.0, build for iOS project, click Run in XCode, and the undefined symbol errors occur.
Tried setting 'Enable swift framework workaround' in the iOS resolver, but no luck.

SDK 13.2.0 build with no errors, but I need to auto add Client Token into info.plist so I have to upgrade to v14.0.0

**Comment by WillsCreative** [comment]
I have NEVER been able to get this SDK to work with my project, it's quite frustrating. Reading the other threads here it seems to be common for this SDK to release versions that don't build.
I'm using `Unity 2022.1.7f1` and `Unity Facebook SDK 14.0` and `Xcode 13.4.1`. Here are my exact steps and results:

1. Build unity project for iOS on Windows.
2. Export project files to Mac OS
3. Open in Xcode and attempt to archive. Fails with errors, can't find any reference to the Facebook SDK (`No such module FBSDKCoreKit` errors)
4. Go to add packages, and using the Github URL I add the Facebook SDK package to my project.
5. Attempt to archive again, gets about 90% complete and then throws the same errors as OP + more:
![Screen Shot 2022-07-08 at 10 49 43 AM](https://user-images.githubusercontent.com/12927636/178044314-1b06d242-3463-469c-b1b0-7a5684900e08.png)


Are there some extra steps not mentioned in the getting started guide that I'm missing? How can I get this to build?

**Comment by snorrsi** [comment]
@gamefish @WillsCreative you need to change Plugins/Canvas folder to only include WebGL .. don't remember how the setting was setup up but you can see how I setup the file at [https://github.com/snorrsi/facebook-upm/blob/v14.0.0/upm/FacebookSDK/Plugins/Canvas/Facebook.Unity.Canvas.dll.meta](https://github.com/snorrsi/facebook-upm/blob/v14.0.0/upm/FacebookSDK/Plugins/Canvas/Facebook.Unity.Canvas.dll.meta) , these are settings copied from my v11.0.1 branch, might need to change the jslib file also.

**Comment by WillsCreative** [comment]
> @gamefish @WillsCreative you need to change Plugins/Canvas folder to only include WebGL .. don't remember how the setting was setup up but you can see how I setup the file at https://github.com/snorrsi/facebook-upm/blob/v14.0.0/upm/FacebookSDK/Plugins/Canvas/Facebook.Unity.Canvas.dll.meta , these are settings copied from my v11.0.1 branch, might need to change the jslib file also.

@snorrsi  I tried with your settings and some of the errors went away, but I still have there:
![Screen Shot 2022-07-08 at 1 15 37 PM](https://user-images.githubusercontent.com/12927636/178064187-d1eb8690-b69e-4ffa-aa4d-500e5d12af71.png)

Any ideas?

**Comment by WillsCreative** [comment]
Just wanted to report back that I was able to get my project to build without errors by switching my XCode version to 13.3.
XCode 13.4.1 would not build, and netiher would 12.3.1, but 13.3 worked.

**Comment by saxahan** [comment]
No its not working as you mentioned.

**Comment by zenlita** [comment]
This is because the dll configuration was not set in Unity. In Unity, go to each dll and select the platform. For the DLLs you are seeing, I believe they are the canvas dlls. Set them as webgl platform and the same for the other dlls. Then rebuild the project and reload on xcode.

**Comment by uchar** [comment]
@gamefish  @saxahan  Did you manage to build your project for iOS?

**Comment by gamefish** [comment]
> @gamefish @saxahan @WillsCreative Did you manage to build your project for iOS? I want to upgrade it on our projects but still worry if it's not ready yet ..

I think @zenlita  and @snorrsi are correct, we have to set platforms of all DLLs manually in Unity. I've managed to build and achieve my project, but have not tested it on the device yet, but I think it will work.

**Comment by JordiFB** [comment]
@gamefish  This error is caused by misconfiguration of SDK Dlls. As @zenlita  explained, Unity change the DLLs platform configuration when you import it into your project. To fix that you can set again the configuration for each dlls.

Please, visit this new GitHub wiki page about common integration issues and how to solve it:  [https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0 ](https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0 )

Thank you for your patient.

**Comment by gamefish** [comment]
> @gamefish This error is caused by misconfiguration of SDK Dlls. As @zenlita explained, Unity change the DLLs platform configuration when you import it into your project. To fix that you can set again the configuration for each dlls.
> 
> Please, visit this new GitHub wiki page about common integration issues and how to solve it: [https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0 ](https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0)
> 
> Thank you for your patient.

Thank you Jordi
