### ISSUE TITLE
Unity SDK 14.0.0 Build-time error on Android platform

### ISSUE THREAD

**Issue by artMacBookPro** [facebook/facebook-sdk-for-unity#627]
Unity ver 2020.3.36
SDK ver 14.0.0
Android platform

1) Install or update Facebook SDK to ver 14.0.0
2) Start build process
3) Recive error:
`Building Library/Bee/artifacts/Android/d8kzr/libil2cpp.so failed with output:
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_init_m7F37E8D602676BCF848A03B7E02C9FBECE38281F':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:329: undefined reference to `init'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_login_m690FB8B413DB1BA3F10CE5EFB74C2678B3FD166B':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:358: undefined reference to `login'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_Logout_m765321CDCDD0B2FF217EC45ED32F7EC33AA74D55':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:375: undefined reference to `logout'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_logout_m88D882A6204D48DC0739D5BE473F301DE9227223':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:375: undefined reference to `logout'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_ActivateApp_m2FB27437D22180800F51B9EECAD053BC08C28FF7':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:384: undefined reference to `activateApp'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_activateApp_mE3803C0C9EA77C9C232A2C565965646541C29826':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:384: undefined reference to `activateApp'
Library/Bee/artifacts/Android/d8kzr/4osi_ity.Canvas.o: In function `CanvasJSWrapper_logAppEvent_m5D5691C6237E414AEC10369CC0BDC60A994B1900':
/Users/mce/Champy/bladebender3d/Library/Bee/artifacts/Android/il2cppOutput/cpp/Facebook.Unity.Canvas.cpp:401: undefined reference to `logAppEvent'`  

etc.
Downgrade to SDK ver 13.2 solves problem.

Unity community forum thread: https://forum.unity.com/threads/facebook-sdk-error-building-library-bee-artifacts-android-d8kzr-libil2cpp-so-failed-with-output.1306053/#post-8271261

**Comment by JordiFB** [comment]
@artMacBookPro  Are you tried to reconfigure the SDK DLLs  for each platform? Seems that your project is trying to compile Canvas in Android platform.

Please visit the new wiki page about common integration issues: https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0

**Comment by nguyentrong101094** [comment]
> @artMacBookPro Are you tried to reconfigure the SDK DLLs for each platform? Seems that your project is trying to compile Canvas in Android platform.
> 
> Please visit the new wiki page about common integration issues: https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0

Can you please update the .meta included in the project to that configuration so developers who use the SDK does not have to go through that step?

**Comment by JordiFB** [comment]
@nguyentrong101094  Sure, we are working on that for the next release.

**Comment by artMacBookPro** [comment]
Fixed in v14.1.0
