### ISSUE TITLE
FB.FeedShare don't use native FB App

### ISSUE THREAD

**Issue by SirKnightDragoon** [facebook/facebook-sdk-for-unity#63]
Unity version: 5.5.1
Platform: Android (4.4 build)

"FB.FeedShare" => use the WebView to share FB feed. (bad)
"FB.ShareLink"   => use Native FB App. (good)

So why FB.FeedShare don't use my FB App ?

**Comment by mingflifb** [comment]
FeedShare is only available for web. It's not a option on the native apps.
