### ISSUE TITLE
WindowsFacebookGameObject.Update() generates 88 bytes a frame

### ISSUE THREAD

**Issue by EllieTellie** [facebook/facebook-sdk-for-unity#643]
## Environment

- Unity Editor Version: `2020.3.37f1`
- Unity SDK Version: `14.1`

## Goals

Have zero garbage generated from a method that runs on the Update loop.

## Expected Results

Facebook not to generates GC every frame and possibly throttle it if it needs to.

## Steps to Reproduce

Run the game in UnityStandaloneWin with the profiler attached and monitor. Notice 88 bytes a frame in Update.ScriptRunBehaviourUpdate.

I assume it's the new Message that gets created in Message.PopMessage() from the Tick() call in the Windows wrapper class.

**Comment by SergioGuerreroFB** [comment]
Fixed in the latest release ([v16.0.0](https://github.com/facebook/facebook-sdk-for-unity/releases/tag/sdk-version-16.0.0)) that contains updated Windows SDK DLLs. Now the new Message is not created each tick, only when there's a message in the queue.
