### ISSUE TITLE
Feature Request: [WebGL] replace `Pointer_stringify(ptrToSomeCString)` with `UTF8ToString(ptrToSomeCString)`

### ISSUE THREAD

**Issue by CodeMasterYi** [facebook/facebook-sdk-for-unity#670]
## Checklist

- [✅] I've updated to the latest released version of the SDK
- [✅] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [✅] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [✅] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

What do you want to achieve?

## Expected Results

What do you expect to happen?

## Code Samples & Details

After Unity 2021.2, in our webgl build, we find some deprecated API used.
we can find error like this in the web console.
```
The JavaScript function 'Pointer_stringify(ptrToSomeCString)' is obsoleted and will be removed in a future Unity version. Please call 'UTF8ToString(ptrToSomeCString)' instead.
```

**Comment by SergioGuerreroFB** [comment]
Thanks for your request @CodeMasterYi. I've replaced this in https://github.com/facebook/facebook-sdk-for-unity/commit/def5dbea64f8466ad7e1aa046e5cfdd319adeb38. Closing the request.

**Comment by CodeMasterYi** [comment]
> Thanks for your request @CodeMasterYi. I've replaced this in https://github.com/facebook/facebook-sdk-for-unity/commit/def5dbea64f8466ad7e1aa046e5cfdd319adeb38. Closing the request.

I have check this commit.
I have one question:
What if someone use lower Unity version without `UTF8ToString`?
