### ISSUE TITLE
[Question](WebGL) `Pointer_stringify` vs `UTF8ToString`

### ISSUE THREAD

**Issue by CodeMasterYi** [facebook/facebook-sdk-for-unity#671]
I have ever created an issue https://github.com/facebook/facebook-sdk-for-unity/issues/670.
But I have an question about the commit that is related to this issue (https://github.com/facebook/facebook-sdk-for-unity/commit/def5dbea64f8466ad7e1aa046e5cfdd319adeb38)
What if someone use lower Unity version without `UTF8ToString`?

**Comment by SergioGuerreroFB** [comment]
Hi @CodeMasterYi.
We officially only support Unity 2019.4.39f1 and up, but UTF8ToString should be included in lower Unity versions too. Let me explain:
Each Unity version has a different version of Emscripten internally. For Unity < 2021.2 it uses Emscripten 1.38.11. UTF8ToString was added in even older versions of Emscripten, so it's safe to just replace the function to UTF8ToString.

Feel free to check the sources I link below and thanks for checking our changes!

Sources:
https://forum.unity.com/threads/how-to-find-which-version-of-emsdk-to-install-to-build-for-webgl-on-ubuntu.1099594/#post-7158388
https://forum.unity.com/threads/pointer_stringify-is-not-defined-pass-string-to-js.701501/#post-4690865
https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#v1294-1212015

**Comment by CodeMasterYi** [comment]
Hi @SergioGuerreroFB 
That sounds great.
Thanks for your reply and your effort.
