### ISSUE TITLE
This example uses Unity Engine OLD input system. If you are using new Input System and you want to use this example, please set your input configuration to BOTH.

### ISSUE THREAD

**Issue by Tommigun1980** [facebook/facebook-sdk-for-unity#681]
Latest everything.

Every time my app is started Facebook prints a warning saying "This example uses Unity Engine OLD input system. If you are using new Input System and you want to use this example, please set your input configuration to BOTH.".

I *am* using the old input manager, please don't spam me and drown out real warnings. This is disrespectful.

**Comment by SergioGuerreroFB** [comment]
The new release will include the following change to improve this: https://github.com/facebook/facebook-sdk-for-unity/commit/ec2f8ed11e3df56ae92b957d4dd14fa97250a852
Thanks for your report!
