### ISSUE TITLE
FB.AppInvite() cause endless spinner on white screen

### ISSUE THREAD

**Issue by featalion** [facebook/facebook-sdk-for-unity#69]
Hi,

I am trying to share App Invite for our mobile application, using:

```csharp
FB.Mobile.AppInvite(new Uri(deepLinkURL), new Uri(previewImageURL), null);
```

When method is called, I see spinner on white screen. This happens on both iOS and Android. Android's logs:

```
V com.facebook.unity.FB: AppInvite({"appLinkUrl":"https://03h7.test-app.link/Iwagrw99yB","previewImageUrl":"https://d1kjt8eb0fx7c1.cloudfront.net/config/rockscience-universe/rsinvite.jpg"})
I ActivityManager: START u0 {cmp=tv.rockscience.RockScienceUniverse/com.facebook.unity.AppInviteDialogActivity (has extras)} from uid 10101 on display 0
I ActivityManager: START u0 {act=com.facebook.platform.PLATFORM_ACTIVITY cat=[android.intent.category.DEFAULT] pkg=com.facebook.katana cmp=com.facebook.katana/com.facebook.platform.common.activity.PlatformWrapperActivity (has extras)} from uid 10101 on display 0
W ActivityManager: Unable to start service Intent { act=android.support.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
I ActivityManager: START u0 {cmp=com.facebook.katana/com.facebook.platform.webdialogs.PlatformWebDialogsActivity (has extras)} from uid 10092 on display 0
```

A user of an application is logged in into one's Facebook account.
When I look into Object Debugger, I see, that link's information is not fetched. When I fetch scrape information, it looks good. For me it means, that `FB.AppInvite()` method does not communicate with Facebook API at all. It happens for both production and development builds of the app.

Do you have any suggestions how to make App Invite feature work?

Facebook Unity SDK version is 7.9.4. Unity3D version is 5.5.1f1.

**Comment by Aleee6** [comment]
Same here :( white screen,spinner, then after like 10-20sec it comes back to the game and nothing happens. Response error says: Dialog failed with unknown error. Sdk 7.10, unity 5.6. Any idea or possible solution?

**Comment by KylinChang** [comment]
App Invite is deprecated now
