### ISSUE TITLE
support refreshing access tokens

### ISSUE THREAD

**Issue by mmerickel** [facebook/facebook-sdk-for-unity#7]
The native iOS and Android SDKs both support refreshing automatically. What is the reason this is not supported on Unity while running on iOS or Android?

Also, the iOS/Android SDKs are using a `grant_type=fb_extend_sso_token ` to refresh the tokens which appears to have no documentation anywhere.

Do I need to abandon the Unity SDK and just use the native/web SDKs directly? Are there any plans to support token refresh in Unity?

**Comment by swiese** [comment]
This is something that we want to support on iOS and Android. We don't have a set eta but it will be coming.

**Comment by mmerickel** [comment]
Thanks @swiese. In the meantime are there any things to know about `fb_extend_sso_token` as I attempt to add this to my own app manually? It appears to be undocumented as of yet.

**Comment by swiese** [comment]
You can add it by calling directly into our native ios and android sdks. I'll look at exposing this functionality in the next release or two but you can see how you could hook it up by looking at adding calls to our native sdks in 
[FB.java](https://github.com/facebook/facebook-sdk-for-unity/blob/master/facebook-android-wrapper/src/com/facebook/unity/FB.java)
[FBUnityInterface.mm](https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Editor/iOS/FBUnityInterface.mm)
And then calling from unity similar to our other methods in 
[IOSFacebook.cs](https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Scripts/Mobile/IOS/IOSFacebook.cs)
[AndroidFacebook.cs](https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Scripts/Mobile/Android/AndroidFacebook.cs)

**Comment by swiese** [comment]
Add in latest unity sdk
