### ISSUE TITLE
Feature Request: Request Newest Facebook SDKv17.0.0 for unity

### ISSUE THREAD

**Issue by heyChenfu** [facebook/facebook-sdk-for-unity#716]
## Checklist

- [🗸] I've updated to the latest released version of the SDK
- [🗸] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [🗸] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [🗸] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Facebook SDK v17.0.0

## Expected Results

Publish Facebook SDK v17.0.0 for unity

**Comment by heyChenfu** [comment]
Facebook SDK v17.0.0 added privacy manifests because of Apple's policy, my project use facebook-unity-sdk-16.0.0, I'm eager to know should I wait for the SDK upgrade, or I  don't need to update the SDK because the library is downloaded through cocoapod and is already the latest, thanks

**Comment by lymancao** [comment]
I have the same request for our Unity project.

**Comment by stanislavsmagin** [comment]
We need new iOS SDK 17.0.0 too. Apple sent us an warning about privacy manifest.

**Comment by daltonbr** [comment]
17.0.0 release is coming - this [commit](https://github.com/facebook/facebook-sdk-for-unity/commit/e21c70dca25ee8769aa14b9612e1f5e8536d39d0) was pushed yesterday.

**Comment by lurenzhangdeshuai** [comment]
> 17.0.0 release is coming - this [commit](https://github.com/facebook/facebook-sdk-for-unity/commit/e21c70dca25ee8769aa14b9612e1f5e8536d39d0) was pushed yesterday.

Thanks ^^  But how to  get the unity package of 17.0.0? use the sample directly?

**Comment by bearhugmo** [comment]
> > 17.0.0 release is coming - this [commit](https://github.com/facebook/facebook-sdk-for-unity/commit/e21c70dca25ee8769aa14b9612e1f5e8536d39d0) was pushed yesterday.
> 
> Thanks ^^ But how to get the unity package of 17.0.0? use the sample directly?

easiest way is to wait for it to get packaged and added to the Releases list.

**Comment by kelvinthh** [comment]
> > 17.0.0 release is coming - this [commit](https://github.com/facebook/facebook-sdk-for-unity/commit/e21c70dca25ee8769aa14b9612e1f5e8536d39d0) was pushed yesterday.
> 
> Thanks ^^ But how to get the unity package of 17.0.0? use the sample directly?

If you have Unity 2021 installed on a Mac, you can clone the repo and build it yourself. There's an instruction in the Readme file.

**Comment by bearhugmo** [comment]
[v17.0.0 release](https://github.com/facebook/facebook-sdk-for-unity/releases/tag/sdk-version-17.0.0)

**Comment by BogdanBobkov** [comment]
Hello! It seems that in release 17.0.0 the version in the AssemblyInfo files has not been updated.
