### ISSUE TITLE
FB.LogOut() mis-capitalized in documentation

### ISSUE THREAD

**Issue by kevinfoley** [facebook/facebook-sdk-for-unity#83]
It's written `LogOut()` in the [actual script,](https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/FB.cs) but `Logout()` in the[ documentation](https://developers.facebook.com/docs/unity/reference/current/FB.Logout)

**Comment by dzhuowen** [comment]
Thanks! The doc has been updated.
