### ISSUE TITLE
User Properties for Analytics

### ISSUE THREAD

**Issue by Rival** [facebook/facebook-sdk-for-unity#88]
Hello,
I would like to set some user properties.

I see it in https://developers.facebook.com/docs/analytics/properties
I suppose they are not implemented yet. How can I use it?

**Comment by kakapro** [comment]
I use API to update user properties but I cannot use these user properties in Segment builder, it's always 0% of user. Anyone got this problem?

P/S: I call API like this
https://graph.facebook.com/v2.10/<appid>/user_properties?data=[{user_unique_id: '123456', custom_data: {CustomerStatus: 'Gold', Age: '25'}}]

**Comment by pforget** [comment]
Hello,
I'm facing the same issue. I use API to update user properties, they are created but all values are unknown.
I'm using Unity, and call the API the same way as above.
The callback for this request returns "success = true".
Did you manage to update your user properties ?
Thanks

**Comment by albertopq** [comment]
Did anybody figured it out?

**Comment by Olgerd82** [comment]
Hi,
Is there any information on this issue?

**Comment by KylinChang** [comment]
Hey all, this is in our roadmap now and will be released in the next release

**Comment by KylinChang** [comment]
v7.16.0 Adds UpdateUserProperties

**Comment by borogove** [comment]
If it ain't documented, it ain't done

**Comment by Romeno** [comment]
this API in analytics seems to be deprecated and yet this method is still not documented
