### ISSUE TITLE
Orientation Bug

### ISSUE THREAD

**Issue by trailbreaker** [facebook/facebook-sdk-for-unity#94]
A summary of the issue we're facing is that after forcing the iOS Unity Player from one fixed orientation to another ('landscape left & right' <-> 'portrait up & down'), the Facebook SDk web view containing the login fails to present.

Unity have managed to reproduce the bug with the reproduction project our dev created. 

Unity's most recent response to the bug report opened with them is as follows:

"...It appear that the Facebook SDK is broken, we're getting in touch with Facebook to report this..."

A link to the bug is below:

https://fogbugz.unity3d.com/default.asp?933588_860eodj6

For reference the original support ticket filed with Unity is documented below.

---------------

Hi Support Team.

We’ve been experiencing issues with the Unity Facebook SDK on iOS. The bug presents when requesting a Facebook login from the SDK when the game has been transitioned to an ‘auto-rotate-portrait-only state’. The bug persists from any point during and after the Unity player has been transitioned to this state.

We are currently building our product against Facebook SDK 7.5.0 in Unity 5.6.2f1 with a patch to the UnityAppController+ViewHandling.mm previously provided by your team to stabilise a screen orientation Bug 835745, delivered in support Request 107874. We have also verified this bug is reproduced against Unity 2017.1f3 with the latest Facebook SDK 7.10.0.

It appears to stem from the fix for Bug 835745, as when we build against ‘vanilla 5.6.2f1’ which doesn’t contain this fix, the bug is not reproducible.

We’ve created a small repro project FbSdk_Repro that is attached.

Reproduction Steps: 
1.	Open project with 2017.1f3 
2.	Ensure project is set to iOS build target. 
3.	Ensure Player Settings -> Resolution and Presentation -> Allowed orientations for Auto Rotation has: 
Portrait = off 
Portrait Upside Down = off 
Landscape Right = enabled 
Landscape Left = enabled 
4.	Build project and run on iOS device 
5.	Launch app (it will be Landscape auto rotate state by default) 
6.	Click login button in UI but don’t press ‘continue’, instead click cancel 
7.	Repeat 6 with device held in various orientations to confirm web view always presents 
8.	Click ‘Set Orientation: Portrait’ button and wait for orientation to change

Now either: 
9.	a) Click Login button and observe the view doesn’t present. 
b) Click ‘Set Orientation: Landscape’ then perform 9. a).

Observe:

The view doesn’t present as it did in steps 6&7 and that exceptions can be caught in the native player despite identical calls being made.

The native error we’re receiving when the SDK requests a web view from the application:

-canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"

To repeat tests the app will now need to be restarted to reproduce the steps as the bug persists.

**Comment by cycoding** [comment]
Please report this bug to https://developers.facebook.com/bugs
