### ISSUE TITLE
Build fails with Unity 5.5:

### ISSUE THREAD

**Issue by wuxingogo** [facebook/facebook-sdk-for-unity#95]
Start new unity project with Unity 5.5.2
Import facebook 7.10.0 sdk
Generate manifest
Add the examples scenes to the build
build fails with:

CommandInvokationFailure: Failed to re-package resources.
/android-sdk-macosx/build-tools/25.0.2/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "/android-sdk-macosx/platforms/android-25/android.jar" -F bin/resources.ap_ --extra-packages com.facebook:com.facebook.android -S "/Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res" -S "/Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-wrapper-7.10.0/res"

stderr[
/Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.

/Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /android-sdk-macosx/platforms/android-25/android.jar
applyFileOverlay for drawable
trying overlaySet Key=com_facebook_auth_dialog_background.xml
trying overlaySet Key=com_facebook_auth_dialog_cancel_background.xml
trying overlaySet Key=com_facebook_auth_dialog_header_background.xml
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.xml
trying overlaySet Key=com_facebook_button_icon_blue.png
trying overlaySet Key=com_facebook_button_icon_white.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_background.xml
trying overlaySet Key=com_facebook_button_login_logo.xml
trying overlaySet Key=com_facebook_button_login_silver_background.xml
trying overlaySet Key=com_facebook_button_send_background.xml
trying overlaySet Key=com_facebook_button_send_icon_blue.png
trying overlaySet Key=com_facebook_button_send_icon_white.png
trying overlaySet Key=com_facebook_close.png
trying overlaySet Key=com_facebook_favicon_blue.xml
trying overlaySet Key=com_facebook_profile_picture_blank_portrait.png
trying overlaySet Key=com_facebook_profile_picture_blank_square.png
trying overlaySet Key=com_facebook_send_button_icon.xml
trying overlaySet Key=com_facebook_tooltip_black_background.9.png
trying overlaySet Key=com_facebook_tooltip_black_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_black_topnub.png
trying overlaySet Key=com_facebook_tooltip_black_xout.png
trying overlaySet Key=com_facebook_tooltip_blue_background.9.png
trying overlaySet Key=com_facebook_tooltip_blue_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_blue_topnub.png
trying overlaySet Key=com_facebook_tooltip_blue_xout.png
trying overlaySet Key=messenger_bubble_large_blue.png
trying overlaySet Key=messenger_bubble_large_white.png
trying overlaySet Key=messenger_bubble_small_blue.png
trying overlaySet Key=messenger_bubble_small_white.png
trying overlaySet Key=messenger_button_blue_bg_round.xml
trying overlaySet Key=messenger_button_blue_bg_selector.xml
trying overlaySet Key=messenger_button_send_round_shadow.png
trying overlaySet Key=messenger_button_white_bg_round.xml
trying overlaySet Key=messenger_button_white_bg_selector.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=com_facebook_activity_layout.xml
trying overlaySet Key=com_facebook_device_auth_dialog_fragment.xml
trying overlaySet Key=com_facebook_login_fragment.xml
trying overlaySet Key=com_facebook_smart_device_dialog_fragment.xml
trying overlaySet Key=com_facebook_tooltip_bubble.xml
trying overlaySet Key=messenger_button_send_blue_large.xml
trying overlaySet Key=messenger_button_send_blue_round.xml
trying overlaySet Key=messenger_button_send_blue_small.xml
trying overlaySet Key=messenger_button_send_white_large.xml
trying overlaySet Key=messenger_button_send_white_round.xml
trying overlaySet Key=messenger_button_send_white_small.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
trying overlaySet Key=com_facebook_button_text_color.xml
trying overlaySet Key=com_facebook_send_button_text_color.xml
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable-mdpi/app_icon.png
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_blue.png: 30% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_blue.png: 23% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_blue.png: 22% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_blue.png: 14% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_icon_white.png: 161% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_icon_white.png: 157% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_icon_white.png: 162% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_icon_white.png: 157% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_like_icon_selected.png: 147% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_like_icon_selected.png: 132% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_like_icon_selected.png: 125% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_like_icon_selected.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_like_icon_selected.png: 114% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_send_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_send_icon_blue.png: 60% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_send_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_send_icon_blue.png: 64% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_send_icon_blue.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_send_icon_blue.png: 89% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_send_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_button_send_icon_white.png: 75% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_send_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_button_send_icon_white.png: 136% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_send_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_button_send_icon_white.png: 128% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_send_icon_white.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xxhdpi-v4/com_facebook_button_send_icon_white.png: 109% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_close.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_close.png: 118% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_close.png
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_close.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_close.png: 132% size of source)
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_close.png: 108% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_profile_picture_blank_portrait.png
    (processed image res/drawable-mdpi/app_icon.png: 90% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_profile_picture_blank_square.png
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_tooltip_black_background.9.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_tooltip_black_background.9.png: 141% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_tooltip_black_background.9.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_tooltip_black_background.9.png: 145% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-xhdpi-v4/com_facebook_tooltip_black_background.9.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_profile_picture_blank_portrait.png: 109% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_tooltip_black_bottomnub.png
    (processed image /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-mdpi-v4/com_facebook_tooltip_black_bottomnub.png: 160% size of source)
Processing image: /Users/apple/Documents/Github/Unity2017Test/SDKManager/Temp/StagingArea/android-libraries/facebook-android-sdk-4.23.0/res/drawable-hdpi-v4/com_facebook_tooltip_black_bottomnub.png
    (processed image /Users/apple/Documents/Github/Uni<message truncated>

**Comment by cycoding** [comment]
Please upgrade to unity 5.6, check https://developers.facebook.com/docs/unity/upgrading-7.x

**Comment by atraver** [comment]
I get this same error in Unity 2017.1.0p2 as well. I was using Facebook SDK v7.9.4, but upgraded to v7.10.0 this morning (deleted the old FacebookSDK directory and the PlayServicesResolver directory and re-imported them from the .unitypackage).
